name: Configure-Term-1
displayName: Configure-Term-1
description: <p>Configure-Term-1</p>
style: {}
fullyQualifiedName: ef2c7acc226a41308a19fb1e2908ae03.Configure-Term-1
synonyms: []
glossary:
  id: 8e571dfe-b03a-459d-b0bc-d95b4832026b
  type: glossary
  name: ef2c7acc226a41308a19fb1e2908ae03
  fullyQualifiedName: ef2c7acc226a41308a19fb1e2908ae03
  description: Word shoulder culture my.
  displayName: ef2c7acc226a41308a19fb1e2908ae03
  deleted: false
children: []
relatedTerms: []
references: []
reviewers: []
owners:
  - id: 18ca6cd1-d696-4a22-813f-c7a42fc09dc4
    type: user
    name: ashish
    fullyQualifiedName: ashish
    description: this is test description. this is test description!this is test description!this
      is test description!this is test description!this is test description!this is
      test description!this is test description!this is test description!this is test
      description!this is test description!
    displayName: Ashish Gupta
    deleted: false
usageCount: 0
tags: []
entityStatus: Approved
mutuallyExclusive: false
domains: []
dataProducts: []
childrenCount: 0
