name: sysutility_ucp_policy_configuration
fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_ucp_policy_configuration
tableType: View
columns:
  - name: utilization_type
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_ucp_policy_configuration.utilization_type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: occurence_frequency
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_ucp_policy_configuration.occurence_frequency
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: trailing_window
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_ucp_policy_configuration.trailing_window
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 57c2f396-9b05-4e00-9903-62b0219fbc25
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: af8db866-dbb4-4bd5-a2ea-22202fbc71ef
  type: database
  name: msdb
  fullyQualifiedName: MSSQL_TEST.msdb
  displayName: msdb
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 854f1f93fcc76464b9107ed6404efba1
processedLineage: false
entityStatus: Approved
