name: sysutility_mi_configuration
fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_mi_configuration
tableType: View
columns:
  - name: ucp_instance_name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_mi_configuration.ucp_instance_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: mdw_database_name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_mi_configuration.mdw_database_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: upload_schema_version
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.sysutility_mi_configuration.upload_schema_version
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 57c2f396-9b05-4e00-9903-62b0219fbc25
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: af8db866-dbb4-4bd5-a2ea-22202fbc71ef
  type: database
  name: msdb
  fullyQualifiedName: MSSQL_TEST.msdb
  displayName: msdb
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: dc19e5d6218ca1c2e273f12ca9810e35
processedLineage: false
entityStatus: Approved
