name: ctx_index_sub_lexer_values
fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values
tableType: View
columns:
  - name: isv_index_owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_index_owner
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: isv_index_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_index_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: isv_language
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_language
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: isv_object
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_object
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: isv_attribute
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_attribute
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: isv_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_index_sub_lexer_values.isv_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5e47000e-823d-436f-9638-5b6ec8cedf56
  type: databaseSchema
  name: ctxsys
  fullyQualifiedName: oracle_test.default.ctxsys
  displayName: ctxsys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 5add404e066a5228695dc439ea7298e5
processedLineage: false
entityStatus: Approved
