name: ctx_extract_policy_values
fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values
tableType: View
columns:
  - name: epv_policy_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_policy_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: epv_policy_owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_policy_owner
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: epv_class
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_class
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: epv_object
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_object
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: epv_attribute
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_attribute
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: epv_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_extract_policy_values.epv_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5e47000e-823d-436f-9638-5b6ec8cedf56
  type: databaseSchema
  name: ctxsys
  fullyQualifiedName: oracle_test.default.ctxsys
  displayName: ctxsys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 0aa0253b0df4844f410e3a8da9d03b88
processedLineage: false
entityStatus: Approved
