name: autoadmin_backup_configuration_summary
fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary
tableType: View
columns:
  - name: ManagedBackupVersion
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.ManagedBackupVersion
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: IsAlwaysOn
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.IsAlwaysOn
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IsDropped
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.IsDropped
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IsEnabled
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.IsEnabled
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: RetentionPeriod
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.RetentionPeriod
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: EncryptionAlgorithm
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.EncryptionAlgorithm
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SchedulingOption
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.SchedulingOption
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DayOfWeek
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(256)
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.DayOfWeek
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DatabaseCount
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MsSQL.msdb.dbo.autoadmin_backup_configuration_summary.DatabaseCount
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: e879efdb-c1f7-4a33-9ce6-fbea5d2fa4ba
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MsSQL.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: 571bcd56-0834-43dc-b560-f0fd9fce7229
  type: database
  name: msdb
  fullyQualifiedName: MsSQL.msdb
  displayName: msdb
  deleted: false
service:
  id: 37fe843d-b482-484c-b77f-fd13d7c2300e
  type: databaseService
  name: MsSQL
  fullyQualifiedName: MsSQL
  displayName: MsSQL
  deleted: false
serviceType: Mssql
schemaDefinition: "----------------------------------------------------------------------------------------------------\r\
  \n--                              autoadmin_backup_configuration_summary\r\n--\r\
  \n-- Contains a summarized version of autoadmin_backup_configurations\r\n-- This\
  \ removes db_ids and outputs only count of databases with each configuration\r\n\
  --\r\nCREATE   VIEW autoadmin_backup_configuration_summary\r\nas\r\nSELECT \r\n\t\
  ManagedBackupVersion,\r\n\tIsAlwaysOn,\r\n\tIsDropped,\r\n\tIsEnabled,\r\n\tRetentionPeriod,\r\
  \n\tEncryptionAlgorithm,\r\n\tSchedulingOption,\r\n\tDayOfWeek,\r\n\tCOUNT(*) AS\
  \ DatabaseCount\r\nFROM autoadmin_backup_configurations\r\nGROUP BY\r\n\tManagedBackupVersion,\r\
  \n\tIsAlwaysOn,\r\n\tIsDropped,\r\n\tIsEnabled,\r\n\tRetentionPeriod,\r\n\tEncryptionAlgorithm,\r\
  \n\tSchedulingOption,\r\n\tDayOfWeek"
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 10c72cd34f123c9fb42736105e896c8b
processedLineage: false
entityStatus: Approved
