name: SERVICES
fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES
tableType: View
columns:
  - name: SERVICE_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_SCHEMA_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_CATALOG_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_CATALOG_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_OWNER
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 13
    dataTypeDisplay: text(13)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMPUTE_POOL_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.MIN_INSTANCES
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.MAX_INSTANCES
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.AUTO_RESUME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DELETED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.DELETED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 23837fbd-b3cb-44cc-8594-7885c2997eaf
  type: databaseSchema
  name: ACCOUNT_USAGE
  fullyQualifiedName: SnowflakeProd.SNOWFLAKE.ACCOUNT_USAGE
  displayName: ACCOUNT_USAGE
  deleted: false
database:
  id: c2c0f880-7eef-47f7-96f7-8a71525148db
  type: database
  name: SNOWFLAKE
  fullyQualifiedName: SnowflakeProd.SNOWFLAKE
  displayName: SNOWFLAKE
  deleted: false
service:
  id: 486b5c07-139b-4e9b-b384-0cb7327fb7b9
  type: databaseService
  name: SnowflakeProd
  fullyQualifiedName: SnowflakeProd
  description: ""
  displayName: SnowflakeProd
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/tmqlsne/ww42057/#/data/databases/SNOWFLAKE/schemas/ACCOUNT_USAGE/view/SERVICES
domains: []
dataProducts: []
sourceHash: d24d1023c827fb12989491074b7aebb2
processedLineage: false
entityStatus: Approved
