name: 6
displayName: ""
fullyQualifiedName: local_redash.6
description: ""
chartType: Other
sourceUrl: https://redash.apps.int.getcollate.io/dashboards/5
owners: []
tags: []
service:
  id: b22c98d2-675c-4ab4-8ae1-d11015e78085
  type: dashboardService
  name: local_redash
  fullyQualifiedName: local_redash
  displayName: local_redash
  deleted: false
serviceType: Redash
domains: []
dataProducts: []
sourceHash: dd41704ff279aba524550c2e25fec28c
dashboards:
  - id: f6d6b728-85a1-42bb-ad5f-8cbcf3f4ee33
    type: dashboard
    name: 5
    fullyQualifiedName: local_redash.5
    description: World Query Data Text
    displayName: World Data
    deleted: false
entityStatus: Approved
