name: 5
displayName: World Query Data
fullyQualifiedName: local_redash.5
description: ""
chartType: Table
sourceUrl: https://redash.apps.int.getcollate.io/dashboards/5
owners: []
tags:
  - tagFQN: RedashTags.worldtag
    name: worldtag
    description: Redash Tag
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: Tier.Tier5
    name: Tier5
    description: |+
      **Private/Unused data assets - No impact beyond individual users**

      - Data assets without any ownership with no usage in the last 60 days

      - Data assets owned by individuals without team ownership

    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: b22c98d2-675c-4ab4-8ae1-d11015e78085
  type: dashboardService
  name: local_redash
  fullyQualifiedName: local_redash
  displayName: local_redash
  deleted: false
serviceType: Redash
domains: []
dataProducts: []
sourceHash: 0b12aa40232964cb5b653b493da7c04b
dashboards:
  - id: f6d6b728-85a1-42bb-ad5f-8cbcf3f4ee33
    type: dashboard
    name: 5
    fullyQualifiedName: local_redash.5
    description: World Query Data Text
    displayName: World Data
    deleted: false
entityStatus: Approved
