name: K126W1F7F3B97BD5E45249D4295190F05BEE3
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.K126W1F7F3B97BD5E45249D4295190F05BEE3
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 23ec503be8ed12fcab908f3cd15b4bed
dashboards:
  - id: 7642aeed-7fc5-481d-bf2f-08a6bfa43e60
    type: dashboard
    name: 68D8A0B40A46F00E3111B787B469D9EF
    fullyQualifiedName: microstrategy_service.68D8A0B40A46F00E3111B787B469D9EF
    displayName: Tec Coffee Quick Insights DEV
    deleted: false
entityStatus: Approved
