name: W005B35047810474DAB274173D9C12F3DWD92562C9843C4CC591A09B50A86EF2D4
displayName: Visualization 2
fullyQualifiedName: microstrategy_service.W005B35047810474DAB274173D9C12F3DWD92562C9843C4CC591A09B50A86EF2D4
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 33d9dd2274ca55cf8f7dd3e515bf94bb
dashboards:
  - id: bac8e066-68cf-4c8d-967c-cbe749cdc49d
    type: dashboard
    name: 5398C49611EB49BE5A1C0080EF05B70E
    fullyQualifiedName: microstrategy_service.5398C49611EB49BE5A1C0080EF05B70E
    displayName: Government World Happiness
    deleted: false
entityStatus: Approved
