name: KE41A751D4AB2DB61E4F809B75182FDEBW1F44F2DEA2D149D884106CF8B58D4C40
displayName: Visualization 2 copy copy
fullyQualifiedName: microstrategy_service.KE41A751D4AB2DB61E4F809B75182FDEBW1F44F2DEA2D149D884106CF8B58D4C40
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 9f0ec8f7ba4502cb6ff4b47b2877a040
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
