name: K3AED48B66942790E46E106B08CBBB688KC4C84ED4D74573835D86B1A72C43668A
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.K3AED48B66942790E46E106B08CBBB688KC4C84ED4D74573835D86B1A72C43668A
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: b8a01e9244a18c10a0f164b4b1ba0049
dashboards:
  - id: 27269e89-748f-43fe-adc2-aede08c82b18
    type: dashboard
    name: B8E507B047721190C8D14F80F11A65D1
    fullyQualifiedName: microstrategy_service.B8E507B047721190C8D14F80F11A65D1
    displayName: Tec Parameters
    deleted: false
entityStatus: Approved
