name: W03DD3A681636454E94C25912B61BE609W3BF9F6D1F1BD4B2BB7B0E85BC028CD7A
displayName: Top States Generating Tournament Teams
fullyQualifiedName: microstrategy_service.W03DD3A681636454E94C25912B61BE609W3BF9F6D1F1BD4B2BB7B0E85BC028CD7A
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 6b4a245243b92154665962a70cdffc1e
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
