name: 211
displayName: Sales Predictions Accuracy
fullyQualifiedName: SampleSuperSetService.211
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 1d08d1a6-9bcb-4e72-a73b-9ce271a2acbf
    type: dashboard
    name: forecast_sales_performance
    fullyQualifiedName: SampleSuperSetService.forecast_sales_performance
    description: ""
    displayName: ETA Predictions Performance
    deleted: false
entityStatus: Unprocessed
