name: 197
displayName: Arcs
fullyQualifiedName: SampleSuperSetService.197
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20197%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: bb52a6df-b931-480d-873b-24039db82402
    type: dashboard
    name: 11
    fullyQualifiedName: SampleSuperSetService.11
    description: ""
    displayName: FCC New Coder Survey 2018
    deleted: false
  - id: 8b675d9c-be4f-4836-8487-a3aaaf432872
    type: dashboard
    name: 12
    fullyQualifiedName: SampleSuperSetService.12
    description: ""
    displayName: Misc Charts
    deleted: false
  - id: 207f6707-f5fc-4667-b0aa-7cb4a39908b5
    type: dashboard
    name: 8
    fullyQualifiedName: SampleSuperSetService.8
    description: ""
    displayName: Orders dashboard
    deleted: false
  - id: 7ddd8c41-cf2e-41e2-9c8e-0a496f84309d
    type: dashboard
    name: 9
    fullyQualifiedName: SampleSuperSetService.9
    description: ""
    displayName: COVID Vaccine Dashboard
    deleted: false
entityStatus: Unprocessed
