name: chart_4
displayName: Chart 4
fullyQualifiedName: SampleLookerService.chart_4
description: This is a sample Chart for Looker
chartType: Histogram
sourceUrl: http://localhost:8088/looker/explore/?form_data=%7B%22slice_id%22%3A%20117%7D
owners: []
tags: []
service:
  id: e5a46435-15e0-4b01-897a-1bc38d5f74e3
  type: dashboardService
  name: SampleLookerService
  fullyQualifiedName: SampleLookerService
  displayName: SampleLookerService
  deleted: false
serviceType: Looker
domains: []
dataProducts: []
dashboards:
  - id: 5d8f1ff9-5f16-4322-a2e3-14dd0cbf418d
    type: dashboard
    name: orders
    fullyQualifiedName: SampleLookerService.orders
    description: This is a sample Dashboard for Looker
    displayName: Orders Dashboard
    deleted: false
entityStatus: Unprocessed
