name: cdb_auto_index_config
fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config
tableType: View
columns:
  - name: parameter_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config.parameter_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: parameter_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config.parameter_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_modified
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(6)
    fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config.last_modified
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: modified_by
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config.modified_by
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: container id
    fullyQualifiedName: oracle_test.default.sys.cdb_auto_index_config.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 8db7da8fa9720983c2f84e37ff2a0049
processedLineage: false
entityStatus: Approved
