name: cdb_audit_mgmt_config_params
fullyQualifiedName: oracle_test.default.sys.cdb_audit_mgmt_config_params
tableType: View
columns:
  - name: parameter_name
    dataType: VARCHAR
    dataLength: 1024
    dataTypeDisplay: varchar2(1024)
    description: Name of the Property
    fullyQualifiedName: oracle_test.default.sys.cdb_audit_mgmt_config_params.parameter_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: parameter_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: Value of the Property
    fullyQualifiedName: oracle_test.default.sys.cdb_audit_mgmt_config_params.parameter_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: audit_trail
    dataType: VARCHAR
    dataLength: 28
    dataTypeDisplay: varchar2(28)
    description: Audit Trail(s) for which the property is configured
    fullyQualifiedName: oracle_test.default.sys.cdb_audit_mgmt_config_params.audit_trail
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: container id
    fullyQualifiedName: oracle_test.default.sys.cdb_audit_mgmt_config_params.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: fccf8cc6dc77256a0d28412934738931
processedLineage: false
entityStatus: Approved
