name: cdb_warning_settings
fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings
tableType: View
columns:
  - name: owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Username of the owner of the object
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.owner
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the object
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.object_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: Object number of the object
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.object_id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_type
    dataType: VARCHAR
    dataLength: 12
    dataTypeDisplay: varchar2(12)
    description: Type of the object
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.object_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: warning
    dataType: VARCHAR
    dataLength: 40
    dataTypeDisplay: varchar2(40)
    description: Warning number or category
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.warning
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: setting
    dataType: VARCHAR
    dataLength: 7
    dataTypeDisplay: varchar2(7)
    description: Value of the warning setting
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.setting
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: container id
    fullyQualifiedName: oracle_test.default.sys.cdb_warning_settings.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 7cd4dbd68240d351b97d4fdde88db0ca
processedLineage: false
entityStatus: Approved
