name: dba_application_roles
fullyQualifiedName: oracle_test.default.sys.dba_application_roles
tableType: View
columns:
  - name: role
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of Application Role
    fullyQualifiedName: oracle_test.default.sys.dba_application_roles.role
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: schema
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Schema name of authorizing package
    fullyQualifiedName: oracle_test.default.sys.dba_application_roles.schema
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: package
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of authorizing package
    fullyQualifiedName: oracle_test.default.sys.dba_application_roles.package
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 9936f6c91d909d6b8169dc01a35dc5cc
processedLineage: false
entityStatus: Approved
