name: gv_$cell_config_info
fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info
tableType: View
columns:
  - name: inst_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.inst_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: cellname
    dataType: VARCHAR
    dataLength: 1024
    dataTypeDisplay: varchar2(1024)
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.cellname
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: cellhash
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.cellhash
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: conftype
    dataType: VARCHAR
    dataLength: 15
    dataTypeDisplay: varchar2(15)
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.conftype
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: confval_hash
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.confval_hash
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: confval
    dataType: CLOB
    dataLength: 1
    dataTypeDisplay: clob
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.confval
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.gv_$cell_config_info.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 85f26dcb2d498d37008b6eb072d1b196
processedLineage: false
entityStatus: Approved
