name: v_$parameter_valid_values
fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values
tableType: View
columns:
  - name: num
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.num
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: VARCHAR
    dataLength: 64
    dataTypeDisplay: varchar2(64)
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ordinal
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.ordinal
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: value
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar2(255)
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: isdefault
    dataType: VARCHAR
    dataLength: 64
    dataTypeDisplay: varchar2(64)
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.isdefault
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$parameter_valid_values.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 0e95dfd663b6486daf0d51a26fccfed3
processedLineage: false
entityStatus: Approved
