name: v_$rman_configuration
fullyQualifiedName: oracle_test.default.sys.v_$rman_configuration
tableType: View
columns:
  - name: CONF#
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$rman_configuration.CONF#
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: VARCHAR
    dataLength: 65
    dataTypeDisplay: varchar2(65)
    fullyQualifiedName: oracle_test.default.sys.v_$rman_configuration.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: value
    dataType: VARCHAR
    dataLength: 1025
    dataTypeDisplay: varchar2(1025)
    fullyQualifiedName: oracle_test.default.sys.v_$rman_configuration.value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$rman_configuration.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: e4c128228a8ec578585c51cfcf31a8a4
processedLineage: false
entityStatus: Approved
