name: TGT_ACCOUNT_PRODUCTCONFIGURATION
fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION
tableType: Regular
columns:
  - name: ID
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.ID
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: ACCOUNT_GUID
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.ACCOUNT_GUID
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MONTH
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.MONTH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: YEAR
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.YEAR
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PRODUCTLINECODE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.PRODUCTLINECODE
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: PRODUCTLINENAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.PRODUCTLINENAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: CONFIGURATIONNAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.CONFIGURATIONNAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: UNITOFMEASUREMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.UNITOFMEASUREMENT
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: DATA_TYPE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.DATA_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DATA_VALUE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.DATA_VALUE
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: CONFIGURATIONDESCRIPTION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: hktest.TEST_DB.IM_TGT.TGT_ACCOUNT_PRODUCTCONFIGURATION.CONFIGURATIONDESCRIPTION
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 2e62e708-09f5-4525-a0f1-2cb833ba362e
  type: databaseSchema
  name: IM_TGT
  fullyQualifiedName: hktest.TEST_DB.IM_TGT
  displayName: IM_TGT
  deleted: false
database:
  id: 001fe81f-478f-495d-ba98-af329b7144b7
  type: database
  name: TEST_DB
  fullyQualifiedName: hktest.TEST_DB
  displayName: TEST_DB
  deleted: false
service:
  id: 28293590-2cd0-4d6a-ad7c-bf50802ee2dd
  type: databaseService
  name: hktest
  fullyQualifiedName: hktest
  description: ""
  displayName: hktest
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/fmfahqk/gi58232/#/data/databases/TEST_DB/schemas/IM_TGT/table/TGT_ACCOUNT_PRODUCTCONFIGURATION
domains: []
dataProducts: []
sourceHash: baba8177709e4d3fa1f3dbdfaf72f8ab
processedLineage: false
entityStatus: Approved
