name: APPLICATION_STATE
fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE
tableType: View
columns:
  - name: CONSUMER_SNOWFLAKE_REGION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_SNOWFLAKE_REGION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ORGANIZATION_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ORGANIZATION_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ACCOUNT_LOCATOR
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ACCOUNT_LOCATOR
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ACCOUNT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ACCOUNT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_SNOWFLAKE_REGION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_SNOWFLAKE_REGION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_ACCOUNT_LOCATOR
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_ACCOUNT_LOCATOR
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_ACCOUNT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_ACCOUNT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PACKAGE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PACKAGE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: APPLICATION_NAME_HASH
    dataType: VARCHAR
    dataLength: 40
    dataTypeDisplay: text(40)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.APPLICATION_NAME_HASH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CREATED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_INSTALLED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_INSTALLED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_VERSION_STATE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_VERSION_STATE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_STATE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_STATE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TARGET_UPGRADE_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.TARGET_UPGRADE_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TARGET_UPGRADE_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.TARGET_UPGRADE_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_STARTED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_STARTED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_ATTEMPT
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_ATTEMPT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_ATTEMPTED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_ATTEMPTED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_FAILURE_REASON
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_FAILURE_REASON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LISTING_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LISTING_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LISTING_DISPLAY_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LISTING_DISPLAY_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: EXCHANGE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.EXCHANGE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 044f5c0d-4f53-49a6-a088-1c76d20dda34
  type: databaseSchema
  name: DATA_SHARING_USAGE
  fullyQualifiedName: TestSnowflake.SNOWFLAKE.DATA_SHARING_USAGE
  displayName: DATA_SHARING_USAGE
  deleted: false
database:
  id: c1a82122-16c9-4db0-9a25-20d3b6ddfb3c
  type: database
  name: SNOWFLAKE
  fullyQualifiedName: TestSnowflake.SNOWFLAKE
  displayName: SNOWFLAKE
  deleted: false
service:
  id: a4689545-b7ad-45ec-8dde-04829253cfa8
  type: databaseService
  name: TestSnowflake
  fullyQualifiedName: TestSnowflake
  description: ""
  displayName: TestSnowflake
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/niughrx/xi67120/#/data/databases/SNOWFLAKE/schemas/DATA_SHARING_USAGE/view/APPLICATION_STATE
domains: []
dataProducts: []
sourceHash: b9bf611ebb64945fac08d8e0a8766001
processedLineage: false
entityStatus: Approved
