name: sysmail_configuration
fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration
tableType: Regular
columns:
  - name: paramname
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(256)
    fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration.paramname
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: paramvalue
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(256)
    fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration.paramvalue
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: description
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(256)
    fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration.description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_mod_datetime
    dataType: DATETIME
    dataLength: 1
    dataTypeDisplay: datetime
    fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration.last_mod_datetime
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: last_mod_user
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MsSQL.msdb.dbo.sysmail_configuration.last_mod_user
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: e879efdb-c1f7-4a33-9ce6-fbea5d2fa4ba
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MsSQL.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: 571bcd56-0834-43dc-b560-f0fd9fce7229
  type: database
  name: msdb
  fullyQualifiedName: MsSQL.msdb
  displayName: msdb
  deleted: false
service:
  id: 37fe843d-b482-484c-b77f-fd13d7c2300e
  type: databaseService
  name: MsSQL
  fullyQualifiedName: MsSQL
  displayName: MsSQL
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 36d544b9498aef7624fb4dd6d8373b05
processedLineage: false
entityStatus: Approved
