name: sysutility_mi_configuration_internal
fullyQualifiedName: MsSQL.msdb.dbo.sysutility_mi_configuration_internal
tableType: Regular
columns:
  - name: configuration_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MsSQL.msdb.dbo.sysutility_mi_configuration_internal.configuration_id
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: ucp_instance_name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MsSQL.msdb.dbo.sysutility_mi_configuration_internal.ucp_instance_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: mdw_database_name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MsSQL.msdb.dbo.sysutility_mi_configuration_internal.mdw_database_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: e879efdb-c1f7-4a33-9ce6-fbea5d2fa4ba
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MsSQL.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: 571bcd56-0834-43dc-b560-f0fd9fce7229
  type: database
  name: msdb
  fullyQualifiedName: MsSQL.msdb
  displayName: msdb
  deleted: false
service:
  id: 37fe843d-b482-484c-b77f-fd13d7c2300e
  type: databaseService
  name: MsSQL
  fullyQualifiedName: MsSQL
  displayName: MsSQL
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 62fca779e9769c9405336e13cd167573
processedLineage: false
entityStatus: Approved
