name: pg_settings
fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings
tableType: Regular
columns:
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.name
    tags: []
    children: []
    customMetrics: []
  - name: setting
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.setting
    tags: []
    children: []
    customMetrics: []
  - name: unit
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.unit
    tags: []
    children: []
    customMetrics: []
  - name: category
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.category
    tags: []
    children: []
    customMetrics: []
  - name: short_desc
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.short_desc
    tags: []
    children: []
    customMetrics: []
  - name: extra_desc
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.extra_desc
    tags: []
    children: []
    customMetrics: []
  - name: context
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.context
    tags: []
    children: []
    customMetrics: []
  - name: vartype
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.vartype
    tags: []
    children: []
    customMetrics: []
  - name: source
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.source
    tags: []
    children: []
    customMetrics: []
  - name: min_val
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.min_val
    tags: []
    children: []
    customMetrics: []
  - name: max_val
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.max_val
    tags: []
    children: []
    customMetrics: []
  - name: enumvals
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.enumvals
    tags: []
    children: []
    customMetrics: []
  - name: boot_val
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.boot_val
    tags: []
    children: []
    customMetrics: []
  - name: reset_val
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.reset_val
    tags: []
    children: []
    customMetrics: []
  - name: sourcefile
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.sourcefile
    tags: []
    children: []
    customMetrics: []
  - name: sourceline
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.sourceline
    tags: []
    children: []
    customMetrics: []
  - name: pending_restart
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: testUnity.postgres_catalog.pg_catalog.pg_settings.pending_restart
    tags: []
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5462ec7a-84fe-426b-bf7b-8d5cc3c78c8c
  type: databaseSchema
  name: pg_catalog
  fullyQualifiedName: testUnity.postgres_catalog.pg_catalog
  displayName: pg_catalog
  deleted: false
database:
  id: 631ee5ac-ca75-4695-9cb0-9c82bd02a746
  type: database
  name: postgres_catalog
  fullyQualifiedName: testUnity.postgres_catalog
  displayName: postgres_catalog
  deleted: false
service:
  id: 686dc5da-a770-4d95-92be-34544ad38d95
  type: databaseService
  name: testUnity
  fullyQualifiedName: testUnity
  description: ""
  displayName: testUnity
  deleted: false
serviceType: UnityCatalog
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 13e72cf660310d32dc8b4111bb806049
processedLineage: false
entityStatus: Approved
