name: FLW_EVENT_DEPLOYMENT
fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT
tableType: Regular
columns:
  - name: ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.ID_
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: NAME_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.NAME_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CATEGORY_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.CATEGORY_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DEPLOY_TIME_
    dataType: DATETIME
    dataLength: 1
    dataTypeDisplay: datetime
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.DEPLOY_TIME_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TENANT_ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.TENANT_ID_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PARENT_DEPLOYMENT_ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.PARENT_DEPLOYMENT_ID_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: f48d00b8-dd4f-4116-89d1-04aefa5bb9b5
  type: databaseSchema
  name: openmetadata_db
  fullyQualifiedName: GyoTestLocal.default.openmetadata_db
  displayName: openmetadata_db
  deleted: false
database:
  id: e284e784-9db4-41f2-99a2-be1fc95fc674
  type: database
  name: default
  fullyQualifiedName: GyoTestLocal.default
  displayName: default
  deleted: false
service:
  id: fc33c634-c86c-4744-b5b9-31265788cd04
  type: databaseService
  name: GyoTestLocal
  fullyQualifiedName: GyoTestLocal
  description: ""
  displayName: GyoTestLocal
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: db2535dd258a56077e725662fb3e3760
processedLineage: false
entityStatus: Approved
