name: openmetadata_settings
fullyQualifiedName: GyoTestLocal.default.openmetadata_db.openmetadata_settings
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: mediumint
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.openmetadata_settings.id
    tags: []
    children: []
    customMetrics: []
  - name: configType
    dataType: VARCHAR
    dataLength: 36
    dataTypeDisplay: varchar(36)
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.openmetadata_settings.configType
    tags: []
    children: []
    customMetrics: []
  - name: json
    dataType: JSON
    dataLength: 1
    dataTypeDisplay: json
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db.openmetadata_settings.json
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: PRIMARY_KEY
    columns:
      - id
      - configType
owners: []
databaseSchema:
  id: f48d00b8-dd4f-4116-89d1-04aefa5bb9b5
  type: databaseSchema
  name: openmetadata_db
  fullyQualifiedName: GyoTestLocal.default.openmetadata_db
  displayName: openmetadata_db
  deleted: false
database:
  id: e284e784-9db4-41f2-99a2-be1fc95fc674
  type: database
  name: default
  fullyQualifiedName: GyoTestLocal.default
  displayName: default
  deleted: false
service:
  id: fc33c634-c86c-4744-b5b9-31265788cd04
  type: databaseService
  name: GyoTestLocal
  fullyQualifiedName: GyoTestLocal
  description: ""
  displayName: GyoTestLocal
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 996f8d94c20cd704fc58ba93e36fd629
processedLineage: false
entityStatus: Approved
