name: openmetadata_settings
fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: mediumint
    fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.id
    tags: []
    children: []
    customMetrics: []
  - name: configType
    dataType: VARCHAR
    dataLength: 36
    dataTypeDisplay: varchar(36)
    fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.configType
    tags: []
    children: []
    customMetrics: []
  - name: json
    dataType: JSON
    dataLength: 1
    dataTypeDisplay: json
    fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.json
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: PRIMARY_KEY
    columns:
      - id
      - configType
owners: []
databaseSchema:
  id: 0cc561a7-0a5d-4286-98b1-81f092a831b2
  type: databaseSchema
  name: openmetadata
  fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata
  displayName: openmetadata
  deleted: false
database:
  id: 08e48188-828c-4ef8-9f88-a9d2ff9b0650
  type: database
  name: cypress_integrations_test_db
  fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db
  displayName: cypress_integrations_test_db
  deleted: false
service:
  id: e0541a7e-df32-43b8-90b2-74c51893be01
  type: databaseService
  name: local_test_akash_mysql_hybrid_runner
  fullyQualifiedName: local_test_akash_mysql_hybrid_runner
  description: ""
  displayName: local_test_akash_mysql_hybrid_runner
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
testSuite:
  id: fb4cb9e2-5b6f-4c71-a4be-62f88b868bc6
  type: testSuite
  name: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.testSuite
  fullyQualifiedName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.testSuite
  displayName: local_test_akash_mysql_hybrid_runner.cypress_integrations_test_db.openmetadata.openmetadata_settings.testSuite
  deleted: false
domains: []
dataProducts: []
sourceHash: 07844c6fcdf557f8d092414acdb11bfe
processedLineage: false
entityStatus: Unprocessed
