name: APPLICATION_STATE
fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE
tableType: View
columns:
  - name: CONSUMER_SNOWFLAKE_REGION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_SNOWFLAKE_REGION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ORGANIZATION_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ORGANIZATION_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ACCOUNT_LOCATOR
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ACCOUNT_LOCATOR
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CONSUMER_ACCOUNT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CONSUMER_ACCOUNT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_SNOWFLAKE_REGION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_SNOWFLAKE_REGION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_ACCOUNT_LOCATOR
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_ACCOUNT_LOCATOR
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PROVIDER_ACCOUNT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PROVIDER_ACCOUNT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PACKAGE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PACKAGE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: APPLICATION_NAME_HASH
    dataType: VARCHAR
    dataLength: 40
    dataTypeDisplay: text(40)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.APPLICATION_NAME_HASH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CREATED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_INSTALLED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.CURRENT_INSTALLED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_VERSION_STATE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_VERSION_STATE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PREVIOUS_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.PREVIOUS_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_STATE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_STATE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TARGET_UPGRADE_VERSION
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.TARGET_UPGRADE_VERSION
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TARGET_UPGRADE_PATCH
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.TARGET_UPGRADE_PATCH
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_STARTED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_STARTED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_ATTEMPT
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_ATTEMPT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_ATTEMPTED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_ATTEMPTED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_FAILURE_REASON
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_FAILURE_REASON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LISTING_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LISTING_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LISTING_DISPLAY_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LISTING_DISPLAY_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: EXCHANGE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.EXCHANGE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_HEALTH_STATUS
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LAST_HEALTH_STATUS
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_HEALTH_STATUS_UPDATED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LAST_HEALTH_STATUS_UPDATED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ENABLED_TELEMETRY_EVENT_DEFINITIONS
    dataType: ARRAY
    arrayDataType: UNKNOWN
    dataLength: 1
    dataTypeDisplay: array
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.ENABLED_TELEMETRY_EVENT_DEFINITIONS
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: UPGRADE_STATE_UPDATED_ON
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.UPGRADE_STATE_UPDATED_ON
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DISABLEMENT_REASONS
    dataType: ARRAY
    arrayDataType: UNKNOWN
    dataLength: 1
    dataTypeDisplay: array
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.DISABLEMENT_REASONS
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LISTING_GLOBAL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE.APPLICATION_STATE.LISTING_GLOBAL_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 9a3085f9-d774-47e0-bf21-05d0b811e893
  type: databaseSchema
  name: DATA_SHARING_USAGE
  fullyQualifiedName: SnowflakeProd.SNOWFLAKE.DATA_SHARING_USAGE
  displayName: DATA_SHARING_USAGE
  deleted: false
database:
  id: c2c0f880-7eef-47f7-96f7-8a71525148db
  type: database
  name: SNOWFLAKE
  fullyQualifiedName: SnowflakeProd.SNOWFLAKE
  displayName: SNOWFLAKE
  deleted: false
service:
  id: 486b5c07-139b-4e9b-b384-0cb7327fb7b9
  type: databaseService
  name: SnowflakeProd
  fullyQualifiedName: SnowflakeProd
  description: ""
  displayName: SnowflakeProd
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/tmqlsne/ww42057/#/data/databases/SNOWFLAKE/schemas/DATA_SHARING_USAGE/view/APPLICATION_STATE
domains: []
dataProducts: []
sourceHash: 3c47fe33bca1e9935c7da26a11ea094f
processedLineage: false
entityStatus: Approved
