name: SERVICES
fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES
tableType: View
columns:
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Database that the service belongs to
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Schema that the service belongs to
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: STATUS
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Status of the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.STATUS
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the role that owns the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Type of role that owns the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the compute pool where the service runs
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: DNS name associated with the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Current number of active instances for the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.CURRENT_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: TARGET_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Target number of active instances for the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.TARGET_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Minimum number of active instances for the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.MIN_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Maximum number of active instances for the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.MAX_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service can be automatically resumed
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.AUTO_RESUME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Comment for this service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Query warehouse of the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Creation time of the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Last altered time of the service
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Time when the service was last resumed
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether this is a Snowpark Container Services Job
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SPEC_DIGEST
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: A unique and immutable identifier to represent the service spec content
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.SPEC_DIGEST
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_UPGRADING
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service is upgrading or not
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.IS_UPGRADING
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_DOMAIN
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The domain of the managing object
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_DOMAIN
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The fully qualified name of the managing object
    fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: db09a908-52d2-4bf5-9557-d2f8878e072e
  type: databaseSchema
  name: INFORMATION_SCHEMA
  fullyQualifiedName: snowflake_all.E2E_DB.INFORMATION_SCHEMA
  description: Views describing the contents of schemas in this database
  displayName: INFORMATION_SCHEMA
  deleted: false
database:
  id: e595ca29-91db-412a-8483-b9050669de8e
  type: database
  name: E2E_DB
  fullyQualifiedName: snowflake_all.E2E_DB
  displayName: E2E_DB
  deleted: false
service:
  id: 4af6c116-941c-445f-8c08-713dd72e2873
  type: databaseService
  name: snowflake_all
  fullyQualifiedName: snowflake_all
  description: ""
  displayName: snowflake_all
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/eggtndd/jd74081/#/data/databases/E2E_DB/schemas/INFORMATION_SCHEMA/view/SERVICES
domains: []
dataProducts: []
sourceHash: 099194b68fece4bde1613c5304a9aee3
processedLineage: false
entityStatus: Approved
