name: data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet
fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet"
tableType: Regular
columns:
  - name: configType
    displayName: configType
    dataType: STRING
    dataTypeDisplay: string
    fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".configType
    tags: []
    children: []
    customMetrics: []
  - name: id
    displayName: id
    dataType: INT
    dataTypeDisplay: int64
    fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".id
    tags: []
    children: []
    customMetrics: []
  - name: json
    displayName: json
    dataType: STRUCT
    dataTypeDisplay: "struct<accessblocktime: double, customfaviconurlpath: string,\
      \ customlogourlpath: string, custommonogramurlpath: string, emailingentity:\
      \ string, enablesmtpserver: bool, jwttokenexpirytime: double, maxloginfailattempts:\
      \ double, openmetadataurl: string, password: string, sendermail: string, serverendpoint:\
      \ string, supporturl: string, transportationstrategy: string, username: string>"
    fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json
    tags: []
    children:
      - name: accessBlockTime
        displayName: accessBlockTime
        dataType: FLOAT
        dataTypeDisplay: double
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.accessBlockTime
        tags: []
        children: []
      - name: customFaviconUrlPath
        displayName: customFaviconUrlPath
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.customFaviconUrlPath
        tags: []
        children: []
      - name: customLogoUrlPath
        displayName: customLogoUrlPath
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.customLogoUrlPath
        tags: []
        children: []
      - name: customMonogramUrlPath
        displayName: customMonogramUrlPath
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.customMonogramUrlPath
        tags: []
        children: []
      - name: emailingEntity
        displayName: emailingEntity
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.emailingEntity
        tags: []
        children: []
      - name: enableSmtpServer
        displayName: enableSmtpServer
        dataType: BOOLEAN
        dataTypeDisplay: bool
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.enableSmtpServer
        tags: []
        children: []
      - name: jwtTokenExpiryTime
        displayName: jwtTokenExpiryTime
        dataType: FLOAT
        dataTypeDisplay: double
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.jwtTokenExpiryTime
        tags: []
        children: []
      - name: maxLoginFailAttempts
        displayName: maxLoginFailAttempts
        dataType: FLOAT
        dataTypeDisplay: double
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.maxLoginFailAttempts
        tags: []
        children: []
      - name: openMetadataUrl
        displayName: openMetadataUrl
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.openMetadataUrl
        tags: []
        children: []
      - name: password
        displayName: password
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.password
        tags: []
        children: []
      - name: senderMail
        displayName: senderMail
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.senderMail
        tags: []
        children: []
      - name: serverEndpoint
        displayName: serverEndpoint
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.serverEndpoint
        tags: []
        children: []
      - name: supportUrl
        displayName: supportUrl
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.supportUrl
        tags: []
        children: []
      - name: transportationStrategy
        displayName: transportationStrategy
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.transportationStrategy
        tags: []
        children: []
      - name: username
        displayName: username
        dataType: STRING
        dataTypeDisplay: string
        fullyQualifiedName: abc.default.awsdatalake-testing."data/demo-path/demo_s3_test/default_openmetadata_db_openmetadata_settings.parquet".json.username
        tags: []
        children: []
    customMetrics: []
owners: []
databaseSchema:
  id: b7bb62d9-5ce4-4da8-a0bd-56aa291fb4f9
  type: databaseSchema
  name: awsdatalake-testing
  fullyQualifiedName: abc.default.awsdatalake-testing
  displayName: awsdatalake-testing
  deleted: false
database:
  id: 21b2a19d-78f7-45bc-8b85-e7cedccfac79
  type: database
  name: default
  fullyQualifiedName: abc.default
  displayName: default
  deleted: false
service:
  id: d9609609-83c5-46dc-b2a7-ea2b261be6d7
  type: databaseService
  name: abc
  fullyQualifiedName: abc
  description: ""
  displayName: abc
  deleted: false
serviceType: Datalake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
fileFormat: parquet
sourceHash: 2764ff7fcb8e40e4997a56ca7955dada
processedLineage: false
entityStatus: Unprocessed
