name: all_stored_settings
fullyQualifiedName: oracle_test.default.sys.all_stored_settings
tableType: View
columns:
  - name: owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Username of the owner of the object
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.owner
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the object
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.object_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: Object number of the object
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.object_id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: object_type
    dataType: VARCHAR
    dataLength: 12
    dataTypeDisplay: varchar2(12)
    description: Type of the object
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.object_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: param_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the parameter
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.param_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: param_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: Value of the parameter
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.param_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: origin_con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: ID of Container where row originates
    fullyQualifiedName: oracle_test.default.sys.all_stored_settings.origin_con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 57744cd857ff8b4b5a4cee1258a96012
processedLineage: false
entityStatus: Approved
