name: all_plsql_object_settings
fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings
tableType: View
columns:
  - name: owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Username of the owner of the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.owner
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: type
    dataType: VARCHAR
    dataLength: 12
    dataTypeDisplay: varchar2(12)
    description: |-
      Type of the object: "PROCEDURE", "FUNCTION",
      "PACKAGE", "PACKAGE BODY", "TRIGGER", "TYPE", "TYPE BODY" or "LIBRARY"
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_optimize_level
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: The optimization level to use to compile the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plsql_optimize_level
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_code_type
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: The object codes are to be compiled natively or are interpreted
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plsql_code_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_debug
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: The object is to be compiled with debug information or not
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plsql_debug
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_warnings
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: The compiler warning settings to use to compile the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plsql_warnings
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: nls_length_semantics
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: The NLS length semantics to use to compile the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.nls_length_semantics
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plsql_ccflags
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: The conditional compilation flag settings to use to compile the object
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plsql_ccflags
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: plscope_settings
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: Settings for using PL/Scope
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.plscope_settings
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: origin_con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: ID of Container where row originates
    fullyQualifiedName: oracle_test.default.sys.all_plsql_object_settings.origin_con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: ab56cb5f4d0a255695edc24257c0f2df
processedLineage: false
entityStatus: Approved
