name: awr_root_wr_settings
fullyQualifiedName: oracle_test.default.sys.awr_root_wr_settings
tableType: View
columns:
  - name: local_awrdbid
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.awr_root_wr_settings.local_awrdbid
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: view_location
    dataType: VARCHAR
    dataLength: 8
    dataTypeDisplay: varchar2(8)
    fullyQualifiedName: oracle_test.default.sys.awr_root_wr_settings.view_location
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.awr_root_wr_settings.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 368aba6b43b48ffa6b7ac5e41749878f
processedLineage: false
entityStatus: Approved
