name: cdb_mining_model_settings
fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings
tableType: View
columns:
  - name: owner
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.owner
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: model_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the model to which the setting belongs
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.model_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: setting_name
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    description: Name of the setting
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.setting_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: setting_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    description: Value of the setting
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.setting_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: setting_type
    dataType: VARCHAR
    dataLength: 7
    dataTypeDisplay: varchar2(7)
    description: Type of the setting
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.setting_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: container id
    fullyQualifiedName: oracle_test.default.sys.cdb_mining_model_settings.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 0a0e10ac8cc1ac076b2b8592256654d5
processedLineage: false
entityStatus: Approved
