name: dba_hist_cell_config
fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config
tableType: View
columns:
  - name: dbid
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.dbid
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: current_snap_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.current_snap_id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: cellname
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: varchar2(256)
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.cellname
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: cellhash
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.cellhash
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: conftype
    dataType: VARCHAR
    dataLength: 15
    dataTypeDisplay: varchar2(15)
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.conftype
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: confval_hash
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.confval_hash
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: confval
    dataType: CLOB
    dataLength: 1
    dataTypeDisplay: clob
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.confval
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_dbid
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.con_dbid
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.dba_hist_cell_config.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 50c90833caff7a16216d665282b2562b
processedLineage: false
entityStatus: Approved
