name: dba_applications
fullyQualifiedName: oracle_test.default.sys.dba_applications
tableType: View
columns:
  - name: app_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    description: Name of the application
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: Id of the application
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_version
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    description: Version of the application
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_version
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_status
    dataType: VARCHAR
    dataLength: 12
    dataTypeDisplay: varchar2(12)
    description: Status of the application
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_status
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_implicit
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: varchar2(1)
    description: Whether the application is implicit
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_implicit
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_capture_service
    dataType: VARCHAR
    dataLength: 64
    dataTypeDisplay: varchar2(64)
    description: Service name used for capture
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_capture_service
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_capture_module
    dataType: VARCHAR
    dataLength: 64
    dataTypeDisplay: varchar2(64)
    description: Module name used for capture
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_capture_module
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: app_capture_error
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: varchar2(1)
    description: Whether statement capture encountered an error
    fullyQualifiedName: oracle_test.default.sys.dba_applications.app_capture_error
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 5ed396bbe11a54f860bd0ece1ce592e0
processedLineage: false
entityStatus: Approved
