name: redaction_values_for_type_full
fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full
tableType: View
columns:
  - name: number_value
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    description: Redaction result for full redaction on NUMBER columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.number_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: binary_float_value
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: binary_float
    description: Redaction result for full redaction on BINARY_FLOAT columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.binary_float_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: binary_double_value
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: binary_double
    description: Redaction result for full redaction on BINARY_DOUBLE columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.binary_double_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: char_value
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: varchar2(1)
    description: Redaction result for full redaction on CHAR columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.char_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: varchar_value
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: varchar2(1)
    description: Redaction result for full redaction on VARCHAR2 columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.varchar_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: nchar_value
    dataType: CHAR
    dataLength: 1
    dataTypeDisplay: nchar(1)
    description: Redaction result for full redaction on NCHAR columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.nchar_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: nvarchar_value
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar2(1)
    description: Redaction result for full redaction on NVARCHAR2 columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.nvarchar_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: date_value
    dataType: DATE
    dataLength: 1
    dataTypeDisplay: date
    description: Redaction result for full redaction on DATE columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.date_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: timestamp_value
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(6)
    description: Redaction result for full redaction on TIMESTAMP columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.timestamp_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: timestamp_with_time_zone_value
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(6) with time zone
    description: Redaction result for full redaction on TIMESTAMP WITH TIME ZONE columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.timestamp_with_time_zone_value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: blob_value
    dataType: BLOB
    dataLength: 1
    dataTypeDisplay: blob
    description: Redaction result for full redaction on BLOB columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.blob_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: clob_value
    dataType: CLOB
    dataLength: 1
    dataTypeDisplay: clob
    description: Redaction result for full redaction on CLOB columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.clob_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: nclob_value
    dataType: CLOB
    dataLength: 1
    dataTypeDisplay: nclob
    description: Redaction result for full redaction on NCLOB columns
    fullyQualifiedName: oracle_test.default.sys.redaction_values_for_type_full.nclob_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 94a14b566bc8ad30ad2e32cbd0f31880
processedLineage: false
entityStatus: Approved
