name: v_$dispatcher_config
fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config
tableType: View
columns:
  - name: conf_indx
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.conf_indx
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: network
    dataType: VARCHAR
    dataLength: 1024
    dataTypeDisplay: varchar2(1024)
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.network
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: dispatchers
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.dispatchers
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: connections
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.connections
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: sessions
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.sessions
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: multiplex
    dataType: VARCHAR
    dataLength: 4
    dataTypeDisplay: varchar2(4)
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.multiplex
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: listener
    dataType: VARCHAR
    dataLength: 1200
    dataTypeDisplay: varchar2(1200)
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.listener
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: service
    dataType: VARCHAR
    dataLength: 512
    dataTypeDisplay: varchar2(512)
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.service
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dispatcher_config.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 081b4d78cbe441fc5e40908d844b6fab
processedLineage: false
entityStatus: Approved
