name: v_$dg_broker_config
fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config
tableType: View
columns:
  - name: database
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.database
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: connect_identifier
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.connect_identifier
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: dataguard_role
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: varchar2(18)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.dataguard_role
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: redo_source
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.redo_source
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: enabled
    dataType: VARCHAR
    dataLength: 5
    dataTypeDisplay: varchar2(5)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.enabled
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: status
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.status
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: version
    dataType: VARCHAR
    dataLength: 30
    dataTypeDisplay: varchar2(30)
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.version
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$dg_broker_config.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 89cf9eb3293d28615ddc46233a3de568
processedLineage: false
entityStatus: Approved
