name: v_$diag_dfw_config_capture
fullyQualifiedName: oracle_test.default.sys.v_$diag_dfw_config_capture
tableType: View
columns:
  - name: capture_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_dfw_config_capture.capture_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: capture_time
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(9) with time zone
    fullyQualifiedName: oracle_test.default.sys.v_$diag_dfw_config_capture.capture_time
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: hash_value
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_dfw_config_capture.hash_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_dfw_config_capture.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 3aa8edb314a8ee8e8784bafba2239c8f
processedLineage: false
entityStatus: Approved
