name: v_$diag_ips_configuration
fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration
tableType: View
columns:
  - name: parameter_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.parameter_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: unit
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.unit
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: value
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: default_value
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.default_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: VARCHAR
    dataLength: 34
    dataTypeDisplay: varchar2(34)
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: description
    dataType: VARCHAR
    dataLength: 203
    dataTypeDisplay: varchar2(203)
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: minimum
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.minimum
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: maximum
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.maximum
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: flags
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.flags
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_ips_configuration.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 476fdef45967a1bb0a1012ee27922b1b
processedLineage: false
entityStatus: Approved
