name: v_$diag_inc_meter_config
fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config
tableType: View
columns:
  - name: cfg_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.cfg_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: transient_incident_life_time
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.transient_incident_life_time
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: flags
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.flags
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: critical_factor
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.critical_factor
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: warning_factor
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.warning_factor
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: weight_factor
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.weight_factor
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: modification_time
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(9) with time zone
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.modification_time
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_startup_time
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp(9) with time zone
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.product_startup_time
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: con_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.sys.v_$diag_inc_meter_config.con_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: a11e2293-c7ca-4d3a-9e0f-ebcfa337159d
  type: databaseSchema
  name: sys
  fullyQualifiedName: oracle_test.default.sys
  displayName: sys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 2b8b7c9db2239729a094ad860517074d
processedLineage: false
entityStatus: Approved
