name: SERVICES
fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES
tableType: View
columns:
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Database that the service belongs to
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Schema that the service belongs to
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: STATUS
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Status of the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.STATUS
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the role that owns the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Type of role that owns the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the compute pool where the service runs
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: DNS name associated with the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Current number of active instances for the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.CURRENT_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: TARGET_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Target number of active instances for the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.TARGET_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MIN_READY_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Minimum number of ready instances to declare service as READY
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.MIN_READY_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Minimum number of active instances for the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.MIN_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Maximum number of active instances for the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.MAX_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service can be automatically resumed
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.AUTO_RESUME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Comment for this service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Query warehouse of the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Creation time of the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Last altered time of the service
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Time when the service was last resumed
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether this is a Snowpark Container Services Job
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SPEC_DIGEST
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: A unique and immutable identifier to represent the service spec content
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.SPEC_DIGEST
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_UPGRADING
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service is upgrading or not
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.IS_UPGRADING
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_DOMAIN
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The domain of the managing object
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_DOMAIN
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The fully qualified name of the managing object
    fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners:
  - id: 8ef5ca04-28cb-40bb-865b-d3a1198fc10a
    type: team
    name: TeamA
    fullyQualifiedName: TeamA
    description: ""
    displayName: TeamA
    deleted: false
    inherited: true
databaseSchema:
  id: e0468f70-cfd5-4005-a10b-7c9e65546e49
  type: databaseSchema
  name: INFORMATION_SCHEMA
  fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA
  description: Views describing the contents of schemas in this database
  displayName: INFORMATION_SCHEMA
  deleted: false
database:
  id: 7388b682-7782-4628-bda7-76b42e2b759a
  type: database
  name: SNOWFLAKE_SAMPLE_DATA
  fullyQualifiedName: Snowflake_test_hr.SNOWFLAKE_SAMPLE_DATA
  description: <p>Checking alert</p>
  displayName: SNOWFLAKE_SAMPLE_DATA
  deleted: false
service:
  id: 435fa0a8-a3e1-4465-bd6a-33924c85e6aa
  type: databaseService
  name: Snowflake_test_hr
  fullyQualifiedName: Snowflake_test_hr
  description: <p>Test the metadata</p>
  displayName: Snowflake_test_hr
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/rtbezht/rf91450/#/data/databases/SNOWFLAKE_SAMPLE_DATA/schemas/INFORMATION_SCHEMA/view/SERVICES
domains: []
dataProducts: []
sourceHash: 86653fa797b73054d262dc64bb47dab0
processedLineage: false
entityStatus: Approved
