name: 3
displayName: Orders Query
fullyQualifiedName: local_redash.3
description: ""
chartType: Table
sourceUrl: https://redash.apps.int.getcollate.io/dashboards/4
owners: []
tags: []
service:
  id: b22c98d2-675c-4ab4-8ae1-d11015e78085
  type: dashboardService
  name: local_redash
  fullyQualifiedName: local_redash
  displayName: local_redash
  deleted: false
serviceType: Redash
domains: []
dataProducts: []
sourceHash: 4bb9c269249f310214ab5d14125bd4ce
dashboards:
  - id: 7112be15-1953-48b7-9442-84be55dbe781
    type: dashboard
    name: 4
    fullyQualifiedName: local_redash.4
    description: This dashboard contains order related to orders
    displayName: Orders Dashboard
    deleted: false
entityStatus: Approved
