name: W72W73
displayName: Web Portal Workflow - Tour Sign Up
fullyQualifiedName: microstrategy_service.W72W73
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 127ac87bf0aa54cbec1d7aea43cfca7a
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
