name: W62W205
displayName: DEPOSITS
fullyQualifiedName: microstrategy_service.W62W205
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 509c32da8b29e692e196c752b6bfcf08
dashboards:
  - id: 7612bbe2-cd92-4cfb-8755-6bc18bf03356
    type: dashboard
    name: 6106087D094887E352562F9014E3839B
    fullyQualifiedName: microstrategy_service.6106087D094887E352562F9014E3839B
    displayName: Finance 360 Branch Performance
    deleted: false
entityStatus: Approved
