name: W8B9F06D770C2493FA76FD4030CC8D7F5K60E3F263FE4C00B56BC457A3D17A4266
displayName: DEPOSITS VS. TOTAL ASSETS
fullyQualifiedName: microstrategy_service.W8B9F06D770C2493FA76FD4030CC8D7F5K60E3F263FE4C00B56BC457A3D17A4266
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: c4f6f6480067b9891b22424d9d206671
dashboards:
  - id: 7612bbe2-cd92-4cfb-8755-6bc18bf03356
    type: dashboard
    name: 6106087D094887E352562F9014E3839B
    fullyQualifiedName: microstrategy_service.6106087D094887E352562F9014E3839B
    displayName: Finance 360 Branch Performance
    deleted: false
entityStatus: Approved
