name: KFA4A427035485229E9047391005D8458K1C896D3C964D4F0FC64A7A9D680DB081
displayName: What If Sales Analysis by Store Type
fullyQualifiedName: microstrategy_service.KFA4A427035485229E9047391005D8458K1C896D3C964D4F0FC64A7A9D680DB081
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 20fd09f8bfcf58b369fea8eaf317ad65
dashboards:
  - id: 27269e89-748f-43fe-adc2-aede08c82b18
    type: dashboard
    name: B8E507B047721190C8D14F80F11A65D1
    fullyQualifiedName: microstrategy_service.B8E507B047721190C8D14F80F11A65D1
    displayName: Tec Parameters
    deleted: false
entityStatus: Approved
