name: W2271866D34EF4B1990731A03B0734C17KF9808E00D344B3EE558D95A9546F29EB
displayName: Time Weighted Returns
fullyQualifiedName: microstrategy_service.W2271866D34EF4B1990731A03B0734C17KF9808E00D344B3EE558D95A9546F29EB
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 2bc967f7c5be92bf740ff3ef5fa1784a
dashboards:
  - id: c7960565-1f6e-4281-a9e8-e8344f4ed6e5
    type: dashboard
    name: 003B0F1DC044BCCC006025A2C0D0B06A
    fullyQualifiedName: microstrategy_service.003B0F1DC044BCCC006025A2C0D0B06A
    displayName: Finance Wealth Management
    deleted: false
entityStatus: Approved
