name: W8B9F06D770C2493FA76FD4030CC8D7F5W894
displayName: Loan-to-Deposit Ratio
fullyQualifiedName: microstrategy_service.W8B9F06D770C2493FA76FD4030CC8D7F5W894
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 81c0447195f51070afa0ed15a4d25832
dashboards:
  - id: 7612bbe2-cd92-4cfb-8755-6bc18bf03356
    type: dashboard
    name: 6106087D094887E352562F9014E3839B
    fullyQualifiedName: microstrategy_service.6106087D094887E352562F9014E3839B
    displayName: Finance 360 Branch Performance
    deleted: false
entityStatus: Approved
