name: W301W1861
displayName: 4
fullyQualifiedName: microstrategy_service.W301W1861
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 9d01b36751057966c1e59cdd10aeaba5
dashboards:
  - id: 42b6069e-49fb-4446-b1d3-acbfa2990f03
    type: dashboard
    name: 59A0A9331F429FF0AF6670A2E67F60CD
    fullyQualifiedName: microstrategy_service.59A0A9331F429FF0AF6670A2E67F60CD
    displayName: BMC Helix ITSM Dashboard
    deleted: false
entityStatus: Approved
