name: W3D4C457874954A93869679AF0DA432BEK6D7DC46A11EB4A7C79410080EF55570E
displayName: 2020
fullyQualifiedName: microstrategy_service.W3D4C457874954A93869679AF0DA432BEK6D7DC46A11EB4A7C79410080EF55570E
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 2dd2e12268b9df9ce34a9f35bf947594
dashboards:
  - id: bac8e066-68cf-4c8d-967c-cbe749cdc49d
    type: dashboard
    name: 5398C49611EB49BE5A1C0080EF05B70E
    fullyQualifiedName: microstrategy_service.5398C49611EB49BE5A1C0080EF05B70E
    displayName: Government World Happiness
    deleted: false
entityStatus: Approved
