name: WAF859E875E304C11996D746F0186F65EW0B42E11EBB824F888CD66A3C8765983F
displayName: Visualization 1 copy copy 1
fullyQualifiedName: microstrategy_service.WAF859E875E304C11996D746F0186F65EW0B42E11EBB824F888CD66A3C8765983F
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 687d9cd0cf4706f76034a4c81e56ff35
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
