name: WA1C364EAA9654C628A0CAA8420F47B07KD0C2C62511E9573F00000080EF9506DE
displayName: Assists Per Game
fullyQualifiedName: microstrategy_service.WA1C364EAA9654C628A0CAA8420F47B07KD0C2C62511E9573F00000080EF9506DE
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 076e7dec2f8b5a48002100505ca7505a
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
