name: W435W236
displayName: Acceptance Rate
fullyQualifiedName: microstrategy_service.W435W236
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: b18d4a1d6b2e9f5a2cd1d2890b1397e1
dashboards:
  - id: b20310b3-73df-4bc9-b739-22fcf46f8435
    type: dashboard
    name: C0CC0E89814C3535A2A7C795716C9F8D
    fullyQualifiedName: microstrategy_service.C0CC0E89814C3535A2A7C795716C9F8D
    displayName: Student Lifecycle Management
    deleted: false
entityStatus: Approved
