name: K53W23931EC5A6AE449DAEF3D3220F91BA89
displayName: Legend
fullyQualifiedName: microstrategy_service.K53W23931EC5A6AE449DAEF3D3220F91BA89
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 19e4d7b1e48e37ef74a68d5cf36b1a55
dashboards:
  - id: ee42857c-139e-4bde-9b4f-2da9a49094f0
    type: dashboard
    name: 37B0371311ED142BE04E0080EFBC62E9
    fullyQualifiedName: microstrategy_service.37B0371311ED142BE04E0080EFBC62E9
    displayName: Infographic National Parks
    deleted: false
entityStatus: Approved
