name: W69W70
displayName: 3 Pointers This Season by School
fullyQualifiedName: microstrategy_service.W69W70
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 0c54aae0d580a5c96a4684cdb99d3e11
dashboards:
  - id: 3c81b612-8065-4578-b5bc-eadf1369b40b
    type: dashboard
    name: 94033C8711E7EFF9000000802FA16C8C
    fullyQualifiedName: microstrategy_service.94033C8711E7EFF9000000802FA16C8C
    displayName: March Madness
    deleted: false
entityStatus: Approved
