name: W0F93CF93228C4E70A71B2AE50D87788DKE7E1684611E9574044CB0080EFF54572
displayName: Points Per Game
fullyQualifiedName: microstrategy_service.W0F93CF93228C4E70A71B2AE50D87788DKE7E1684611E9574044CB0080EFF54572
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 9a3e8db371cfea84944db9168861b8a6
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
