name: W3D4C457874954A93869679AF0DA432BEWB97302307F8444E8971B1F4A27C08B94
displayName: Visualization 4
fullyQualifiedName: microstrategy_service.W3D4C457874954A93869679AF0DA432BEWB97302307F8444E8971B1F4A27C08B94
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 75af6c8f3bde42641b8a6d6c56bb6d7f
dashboards:
  - id: bac8e066-68cf-4c8d-967c-cbe749cdc49d
    type: dashboard
    name: 5398C49611EB49BE5A1C0080EF05B70E
    fullyQualifiedName: microstrategy_service.5398C49611EB49BE5A1C0080EF05B70E
    displayName: Government World Happiness
    deleted: false
entityStatus: Approved
