name: W92W97
displayName: Tourism Analysis by Age
fullyQualifiedName: microstrategy_service.W92W97
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 8d8de75a02234f3c1bbc579f13887266
dashboards:
  - id: 83872df6-bb9f-4fb2-b6ac-bd61954c8ab5
    type: dashboard
    name: 85D9C39DC546D9E07FB19FBF36F13A14
    fullyQualifiedName: microstrategy_service.85D9C39DC546D9E07FB19FBF36F13A14
    displayName: Travel Agency Transactions
    deleted: false
entityStatus: Approved
