name: K6D038E5B2744ECC7608CA9AA7B106521K38C13B6DC945E7B77E2C128871CCEC84
displayName: DOSSIERS
fullyQualifiedName: microstrategy_service.K6D038E5B2744ECC7608CA9AA7B106521K38C13B6DC945E7B77E2C128871CCEC84
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: bb009587b4d3a5a4161f5fe0a3ee8c64
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
