name: W2261K220
displayName: 5
fullyQualifiedName: microstrategy_service.W2261K220
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 803364a086f00d68544d5847c6535874
dashboards:
  - id: 42b6069e-49fb-4446-b1d3-acbfa2990f03
    type: dashboard
    name: 59A0A9331F429FF0AF6670A2E67F60CD
    fullyQualifiedName: microstrategy_service.59A0A9331F429FF0AF6670A2E67F60CD
    displayName: BMC Helix ITSM Dashboard
    deleted: false
entityStatus: Approved
