name: W33088599997A42F88510AEC7A18274C87533D4ADB845439D8B05F5FC374477FD
displayName: MicroChart Bar + Min/Max Cell @Mobile Compatible
fullyQualifiedName: microstrategy_service.W33088599997A42F88510AEC7A18274C87533D4ADB845439D8B05F5FC374477FD
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 68aed3be40223bafd964686f2da376c2
dashboards:
  - id: 69b96b32-9865-4332-9a29-9d3814683eb0
    type: dashboard
    name: 965451BD2347586FBC9B158D1C305FA0
    fullyQualifiedName: microstrategy_service.965451BD2347586FBC9B158D1C305FA0
    displayName: Custom SVG Visualizations
    deleted: false
entityStatus: Approved
