name: W204K64
displayName: Visualization 4
fullyQualifiedName: microstrategy_service.W204K64
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 746ed5a685af3ed463f260d83d91ccdd
dashboards:
  - id: d97fbc81-90f9-4466-a753-9f5be3daca14
    type: dashboard
    name: 2154CA4B3544FE8F24F288B39A00BC9C
    fullyQualifiedName: microstrategy_service.2154CA4B3544FE8F24F288B39A00BC9C
    displayName: Tec Coffee Quick Insights_lastversionWithHTMLContainer
    deleted: false
entityStatus: Approved
