name: WAF859E875E304C11996D746F0186F65EW6903FE119D3F461890407CABFF6E65AB
displayName: Visualization 1 copy copy
fullyQualifiedName: microstrategy_service.WAF859E875E304C11996D746F0186F65EW6903FE119D3F461890407CABFF6E65AB
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 02b2e6977384dfe2774d2ae8e5f6411c
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
