name: W2108W2110
displayName: Main Grid
fullyQualifiedName: microstrategy_service.W2108W2110
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 02ebf4e916a9e7af9c9a1c760c4e95bd
dashboards:
  - id: 42b6069e-49fb-4446-b1d3-acbfa2990f03
    type: dashboard
    name: 59A0A9331F429FF0AF6670A2E67F60CD
    fullyQualifiedName: microstrategy_service.59A0A9331F429FF0AF6670A2E67F60CD
    displayName: BMC Helix ITSM Dashboard
    deleted: false
entityStatus: Approved
