name: K53W81CEC3446D3D4074A4AF1CB8062C6BFE
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.K53W81CEC3446D3D4074A4AF1CB8062C6BFE
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: a911480d66298451e54ae4bac87b52ae
dashboards:
  - id: ee42857c-139e-4bde-9b4f-2da9a49094f0
    type: dashboard
    name: 37B0371311ED142BE04E0080EFBC62E9
    fullyQualifiedName: microstrategy_service.37B0371311ED142BE04E0080EFBC62E9
    displayName: Infographic National Parks
    deleted: false
entityStatus: Approved
