name: WC1FBED72B3B640DCB7E5409822DFE310WE273C79328A34738AD26FFE485ADF773
displayName: Income
fullyQualifiedName: microstrategy_service.WC1FBED72B3B640DCB7E5409822DFE310WE273C79328A34738AD26FFE485ADF773
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: cb2c2c7c71d565b8ed1e8491c3d0d02c
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
