name: K7280A6F5EE406D038BD1CE83BA36ED4FK31563D31824F779C41F80DB86FB225E0
displayName: MOBILE APPS
fullyQualifiedName: microstrategy_service.K7280A6F5EE406D038BD1CE83BA36ED4FK31563D31824F779C41F80DB86FB225E0
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 44919b5e4394624437245af35f49bc86
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
