name: W005B35047810474DAB274173D9C12F3DW480CDA714F814FB5B19166BF61AE14F3
displayName: Visualization 2 copy copy 1 copy copy
fullyQualifiedName: microstrategy_service.W005B35047810474DAB274173D9C12F3DW480CDA714F814FB5B19166BF61AE14F3
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 13e7f4358c1d37bb73e5bdedd6c8328f
dashboards:
  - id: bac8e066-68cf-4c8d-967c-cbe749cdc49d
    type: dashboard
    name: 5398C49611EB49BE5A1C0080EF05B70E
    fullyQualifiedName: microstrategy_service.5398C49611EB49BE5A1C0080EF05B70E
    displayName: Government World Happiness
    deleted: false
entityStatus: Approved
