name: WE4D8A639C04B4CAB900AC5C80726C783K310F06F911EB1CF3DED80080EF459DDC
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.WE4D8A639C04B4CAB900AC5C80726C783K310F06F911EB1CF3DED80080EF459DDC
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: c43ebc4303235d22873104456aa67112
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
