name: KEECFF4BB4747172F4626E6B6F58B3A84W2F45D285328846ADB3A72913670BAB7A
displayName: Comments per Author
fullyQualifiedName: microstrategy_service.KEECFF4BB4747172F4626E6B6F58B3A84W2F45D285328846ADB3A72913670BAB7A
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: eec39d9f54426d9546aacbd72fad4814
dashboards:
  - id: d97fbc81-90f9-4466-a753-9f5be3daca14
    type: dashboard
    name: 2154CA4B3544FE8F24F288B39A00BC9C
    fullyQualifiedName: microstrategy_service.2154CA4B3544FE8F24F288B39A00BC9C
    displayName: Tec Coffee Quick Insights_lastversionWithHTMLContainer
    deleted: false
entityStatus: Approved
