name: W77BBA155CC584D9598F65AF0B108322CK1F70B1834862979BA3CE37AE82A9DD4A
displayName: Visualisierung 4
fullyQualifiedName: microstrategy_service.W77BBA155CC584D9598F65AF0B108322CK1F70B1834862979BA3CE37AE82A9DD4A
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 5f8b817b3acd4fe70522dbb3ac0c7910
dashboards:
  - id: d97fbc81-90f9-4466-a753-9f5be3daca14
    type: dashboard
    name: 2154CA4B3544FE8F24F288B39A00BC9C
    fullyQualifiedName: microstrategy_service.2154CA4B3544FE8F24F288B39A00BC9C
    displayName: Tec Coffee Quick Insights_lastversionWithHTMLContainer
    deleted: false
entityStatus: Approved
