name: WE4D8A639C04B4CAB900AC5C80726C783K310EFF5111EB1CF3E38C0080EF459DE0
displayName: SCENARIO
fullyQualifiedName: microstrategy_service.WE4D8A639C04B4CAB900AC5C80726C783K310EFF5111EB1CF3E38C0080EF459DE0
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 6dc55621c1ffdf3315dff227cdf49dae
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
