name: d50a6831-aaa9-42a5-a9dd-05f79bc8937a
displayName: Carlos Gross Margin Trend
fullyQualifiedName: powerbi_prod.d50a6831-aaa9-42a5-a9dd-05f79bc8937a
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/d7d155f1-1b8c-49dc-90cd-da4b1c81fd54
owners: []
tags:
  - tagFQN: '`custom`.tag1'
    name: tag1
    displayName: tag1
    description: <p>tag1</p>
    style:
      color: "#fd3f3f"
      iconURL: https://cdn-icons-png.flaticon.com/512/9029/9029931.png
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: 89d9de05-72fb-4da7-9066-4f8c202000ea
  type: dashboardService
  name: powerbi_prod
  fullyQualifiedName: powerbi_prod
  description: ""
  displayName: powerbi_prod
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 7e4c02a6de064622236579fc381a5087
dashboards:
  - id: 2f667687-87de-4b18-a25d-697f8744d6cd
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: powerbi_prod.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
  - id: 55ae8335-7ab6-43bc-96c5-8be4d4e28421
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: powerbi_prod.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
  - id: 3019c3a9-1240-49d6-b876-0cd88db28d5f
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: powerbi_prod.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
  - id: 1627596d-4ac1-425e-b415-61fdcecb46aa
    type: dashboard
    name: d142fcb5-0370-4421-bebf-3ace1c03cf75
    fullyQualifiedName: powerbi_prod.d142fcb5-0370-4421-bebf-3ace1c03cf75
    displayName: Lineage testing dashboard
    deleted: false
entityStatus: Approved
