name: 52b6ab74-b899-45e5-8bd8-a606cc0418e9
displayName: Andrew Gross Margin Trend
fullyQualifiedName: powerbi_prod.52b6ab74-b899-45e5-8bd8-a606cc0418e9
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/e1a9219d-adf9-48e3-823b-7f2b0a8ac6c0
owners: []
tags: []
service:
  id: 89d9de05-72fb-4da7-9066-4f8c202000ea
  type: dashboardService
  name: powerbi_prod
  fullyQualifiedName: powerbi_prod
  description: ""
  displayName: powerbi_prod
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 332986b4c2d29afe6f90a6ca5cf591dc
dashboards:
  - id: 2f667687-87de-4b18-a25d-697f8744d6cd
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: powerbi_prod.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
  - id: 55ae8335-7ab6-43bc-96c5-8be4d4e28421
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: powerbi_prod.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
  - id: 3019c3a9-1240-49d6-b876-0cd88db28d5f
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: powerbi_prod.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
  - id: 1627596d-4ac1-425e-b415-61fdcecb46aa
    type: dashboard
    name: d142fcb5-0370-4421-bebf-3ace1c03cf75
    fullyQualifiedName: powerbi_prod.d142fcb5-0370-4421-bebf-3ace1c03cf75
    displayName: Lineage testing dashboard
    deleted: false
entityStatus: Approved
