name: 166
displayName: '% Rural'
fullyQualifiedName: sample_superset.166
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20166%7D
owners: []
tags: []
service:
  id: 8db95335-b86e-476f-b5c6-39c029d866ff
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"37fa7fb3-c53b-4a3b-b4d5-7be255e8effa\",\"type\":\"dashboard\"\
        ,\"name\":\"10\",\"fullyQualifiedName\":\"sample_superset.10\",\"description\"\
        :\"\",\"displayName\":\"deck.gl Demo\",\"deleted\":false},{\"id\":\"3e5f65da-84aa-43d9-9f01-e4833f9a7f45\"\
        ,\"type\":\"dashboard\",\"name\":\"31\",\"fullyQualifiedName\":\"sample_superset.31\"\
        ,\"description\":\"\",\"displayName\":\"Sales Dashboard\",\"deleted\":false}]"
  previousVersion: 1.5
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 37fa7fb3-c53b-4a3b-b4d5-7be255e8effa
    type: dashboard
    name: 10
    fullyQualifiedName: sample_superset.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 3e5f65da-84aa-43d9-9f01-e4833f9a7f45
    type: dashboard
    name: 31
    fullyQualifiedName: sample_superset.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
entityStatus: Unprocessed
