name: 210
displayName: ETA Predictions Accuracy
fullyQualifiedName: SampleSuperSetService.210
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: a2032030-a5b3-4692-9d1a-5e67f08e320e
    type: dashboard
    name: eta_predictions_performance
    fullyQualifiedName: SampleSuperSetService.eta_predictions_performance
    description: ""
    displayName: ETA Predictions Performance
    deleted: false
entityStatus: Unprocessed
