name: 92
displayName: ✈️ Relocation ability
fullyQualifiedName: sample_superset.92
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%2092%7D
owners: []
tags: []
service:
  id: 8db95335-b86e-476f-b5c6-39c029d866ff
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"3e5f65da-84aa-43d9-9f01-e4833f9a7f45\",\"type\":\"dashboard\"\
        ,\"name\":\"31\",\"fullyQualifiedName\":\"sample_superset.31\",\"description\"\
        :\"\",\"displayName\":\"Sales Dashboard\",\"deleted\":false},{\"id\":\"184c8289-aa60-4c63-92b2-0e1edb7f3dea\"\
        ,\"type\":\"dashboard\",\"name\":\"33\",\"fullyQualifiedName\":\"sample_superset.33\"\
        ,\"description\":\"\",\"displayName\":\"Slack Dashboard\",\"deleted\":false}]"
  previousVersion: 1.5
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 3e5f65da-84aa-43d9-9f01-e4833f9a7f45
    type: dashboard
    name: 31
    fullyQualifiedName: sample_superset.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
  - id: 184c8289-aa60-4c63-92b2-0e1edb7f3dea
    type: dashboard
    name: 33
    fullyQualifiedName: sample_superset.33
    description: ""
    displayName: Slack Dashboard
    deleted: false
entityStatus: Unprocessed
