name: 92
displayName: ✈️ Relocation ability
fullyQualifiedName: SampleSuperSetService.92
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%2092%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 0d9cba41-8f73-49b1-a5bb-a0b5a13e0d36
    type: dashboard
    name: 31
    fullyQualifiedName: SampleSuperSetService.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
  - id: 2295de76-4a99-4551-87e9-7287f9db6653
    type: dashboard
    name: 33
    fullyQualifiedName: SampleSuperSetService.33
    description: ""
    displayName: Slack Dashboard
    deleted: false
entityStatus: Unprocessed
