name: chart_3
displayName: ✈️ Chart 3
fullyQualifiedName: sample_looker.chart_3
description: This is a sample Chart for Looker
chartType: Other
sourceUrl: http://localhost:8088/looker/explore/?form_data=%7B%22slice_id%22%3A%2092%7D
owners: []
tags:
  - tagFQN: PII.Sensitive
    name: Sensitive
    description: "PII which if lost, compromised, or disclosed without authorization,\
      \ could result in substantial harm, embarrassment, inconvenience, or unfairness\
      \ to an individual."
    style:
      color: "#ff0000"
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: Person.SocialMedia
    name: SocialMedia
    description: Person's social media profile information.
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: PersonalData.Personal
    name: Personal
    description: Data that can be used to directly or indirectly identify a person.
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: 2d102aaa-e683-425c-a8bf-e4afa43dde99
  type: dashboardService
  name: sample_looker
  fullyQualifiedName: sample_looker
  displayName: sample_looker
  deleted: false
serviceType: Looker
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"586e2826-892c-4a40-b093-c59d1425f6f2\",\"type\":\"dashboard\"\
        ,\"name\":\"orders\",\"fullyQualifiedName\":\"sample_looker.orders\",\"description\"\
        :\"This is a sample Dashboard for Looker\",\"displayName\":\"Orders Dashboard\"\
        ,\"deleted\":false}]"
  previousVersion: 1.7
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 586e2826-892c-4a40-b093-c59d1425f6f2
    type: dashboard
    name: orders
    fullyQualifiedName: sample_looker.orders
    description: This is a sample Dashboard for Looker
    displayName: Orders Dashboard
    deleted: false
entityStatus: Unprocessed
