name: 211
displayName: Sales Predictions Accuracy
fullyQualifiedName: sample_superset.211
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags:
  - tagFQN: TestNewGlossary.OpenMetadata_dataInsight_01.TestNewGlossaryTerm
    name: TestNewGlossaryTerm
    displayName: TestNewGlossaryTerm
    description: TestNewGlossaryTerm
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: advanceSearch.advanceSearchTag
    name: advanceSearchTag
    displayName: advanceSearchTagDisplayName
    description: advanceSearchTag
    style: {}
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: 8db95335-b86e-476f-b5c6-39c029d866ff
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"2c61aff2-14be-4cb7-adfc-e2140dec6bc0\",\"type\":\"dashboard\"\
        ,\"name\":\"forecast_sales_performance\",\"fullyQualifiedName\":\"sample_superset.forecast_sales_performance\"\
        ,\"description\":\"\",\"displayName\":\"ETA Predictions Performance\",\"deleted\"\
        :false}]"
  previousVersion: 1.5
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 2c61aff2-14be-4cb7-adfc-e2140dec6bc0
    type: dashboard
    name: forecast_sales_performance
    fullyQualifiedName: sample_superset.forecast_sales_performance
    description: ""
    displayName: ETA Predictions Performance
    deleted: false
entityStatus: Unprocessed
