name: 114
displayName: "# of Games That Hit 100k in Sales By Release Year"
fullyQualifiedName: sample_superset.114
description: ""
chartType: Area
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20114%7D
owners: []
tags: []
service:
  id: 8db95335-b86e-476f-b5c6-39c029d866ff
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"37fa7fb3-c53b-4a3b-b4d5-7be255e8effa\",\"type\":\"dashboard\"\
        ,\"name\":\"10\",\"fullyQualifiedName\":\"sample_superset.10\",\"description\"\
        :\"\",\"displayName\":\"deck.gl Demo\",\"deleted\":false},{\"id\":\"184c8289-aa60-4c63-92b2-0e1edb7f3dea\"\
        ,\"type\":\"dashboard\",\"name\":\"33\",\"fullyQualifiedName\":\"sample_superset.33\"\
        ,\"description\":\"\",\"displayName\":\"Slack Dashboard\",\"deleted\":false}]"
  previousVersion: 2.3
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 37fa7fb3-c53b-4a3b-b4d5-7be255e8effa
    type: dashboard
    name: 10
    fullyQualifiedName: sample_superset.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 184c8289-aa60-4c63-92b2-0e1edb7f3dea
    type: dashboard
    name: 33
    fullyQualifiedName: sample_superset.33
    description: ""
    displayName: Slack Dashboard
    deleted: false
entityStatus: Unprocessed
