name: 51eed4b3-c714-41a7-8642-4a74eaf8db35
displayName: Business
fullyQualifiedName: Tableau.51eed4b3-c714-41a7-8642-4a74eaf8db35
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/WorldIndicators/Business
owners:
  - id: 02572492-b9af-4e28-8231-b6d311e81d51
    type: team
    name: abc.def.ghi
    fullyQualifiedName: '"abc.def.ghi"'
    description: ""
    displayName: abc.def.ghi
    deleted: false
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
incrementalChangeDescription:
  fieldsAdded:
    - name: owners
      newValue: "[{\"id\":\"02572492-b9af-4e28-8231-b6d311e81d51\",\"type\":\"team\"\
        ,\"name\":\"abc.def.ghi\",\"fullyQualifiedName\":\"\\\"abc.def.ghi\\\"\",\"\
        description\":\"\",\"displayName\":\"abc.def.ghi\",\"deleted\":false}]"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
domains: []
dataProducts: []
sourceHash: 6f47ed15a457557c54a2d12f87dbd3f5
dashboards:
  - id: 0f8e11d2-f2b2-4f90-bf7c-292685d660f4
    type: dashboard
    name: c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    fullyQualifiedName: Tableau.c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    displayName: World Indicators
    deleted: false
entityStatus: Approved
