name: 06c98159-9057-4e05-8e1b-0e7e0cb0a600
displayName: What If Forecast
fullyQualifiedName: Tableau.06c98159-9057-4e05-8e1b-0e7e0cb0a600
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/Superstore/WhatIfForecast
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: ad5c59ec7c60d81fec0fa731ee546954
dashboards:
  - id: 84e3e3b0-c043-455f-a21e-8aa9d97fe142
    type: dashboard
    name: f3598b75-e0c8-4d50-99ee-5d230b7ec767
    fullyQualifiedName: Tableau.f3598b75-e0c8-4d50-99ee-5d230b7ec767
    displayName: Superstore
    deleted: false
entityStatus: Approved
