name: e5670aa3-3ad9-4872-9992-98b9304e69bb
displayName: Commission Model
fullyQualifiedName: Tableau.e5670aa3-3ad9-4872-9992-98b9304e69bb
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/Superstore/CommissionModel
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 69b5e325dae50d6337a78acb5129239e
dashboards:
  - id: 84e3e3b0-c043-455f-a21e-8aa9d97fe142
    type: dashboard
    name: f3598b75-e0c8-4d50-99ee-5d230b7ec767
    fullyQualifiedName: Tableau.f3598b75-e0c8-4d50-99ee-5d230b7ec767
    displayName: Superstore
    deleted: false
entityStatus: Approved
