name: 2b288c93-4274-4295-84b3-88ab2f0f2649
displayName: Product
fullyQualifiedName: Tableau.2b288c93-4274-4295-84b3-88ab2f0f2649
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/Superstore/Product
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 6385c7464afe44528f1ea67288275c25
dashboards:
  - id: 84e3e3b0-c043-455f-a21e-8aa9d97fe142
    type: dashboard
    name: f3598b75-e0c8-4d50-99ee-5d230b7ec767
    fullyQualifiedName: Tableau.f3598b75-e0c8-4d50-99ee-5d230b7ec767
    displayName: Superstore
    deleted: false
entityStatus: Approved
