name: 4fa180cd-7488-4be6-b5cc-0ec9f9054c6c
displayName: 4fa180cd-7488-4be6-b5cc-0ec9f9054c6c
fullyQualifiedName: test_pbi.4fa180cd-7488-4be6-b5cc-0ec9f9054c6c
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/70fa3baf-6e21-419e-832d-60a418a0cdd0
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 527411b5a6741c5152155cbb61ef2df6
dashboards:
  - id: 44101b1b-96d8-43fd-9081-948e252380fb
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: test_pbi.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
