name: 0871637b-8697-48c4-b70a-fce73000f6e2
displayName: Population
fullyQualifiedName: Test_tableau.0871637b-8697-48c4-b70a-fce73000f6e2
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/Population
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: d9a7259372f83637e5fc71e18bf75c93
dashboards:
  - id: 1678d28a-92e8-420e-91de-13037e162c76
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: Test_tableau.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Approved
