name: 29ae2528-724d-441f-8aa5-66776afc7801
displayName: Year Over Year Revenue Growth
fullyQualifiedName: test_pbi.29ae2528-724d-441f-8aa5-66776afc7801
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/70fa3baf-6e21-419e-832d-60a418a0cdd0
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 600cea96db9c5d3f01cadda3f88d9f3a
dashboards:
  - id: 44101b1b-96d8-43fd-9081-948e252380fb
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: test_pbi.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
