name: 37788d6d-bf06-45a8-8de6-4db12655e81e
displayName: Annelie Gross Margin Trend
fullyQualifiedName: test_pbi.37788d6d-bf06-45a8-8de6-4db12655e81e
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/d7d155f1-1b8c-49dc-90cd-da4b1c81fd54
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 6c55adedf4e68fc858c38f58d0ac0669
dashboards:
  - id: 44101b1b-96d8-43fd-9081-948e252380fb
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: test_pbi.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
