name: c7c3e3bc-0f72-4e96-a48f-042698dcc19d
displayName: Total Defect Qty
fullyQualifiedName: test_pbi.c7c3e3bc-0f72-4e96-a48f-042698dcc19d
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/059965af-3532-4da4-a532-2754721f5e27
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 43654dbc20d1bb5e9f94e0d05d1e407f
dashboards:
  - id: 583413ff-daad-4d8c-afa3-d21556b747a4
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: test_pbi.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
entityStatus: Approved
