name: b6c6549b-8078-4d17-935c-c6db9a370093
displayName: b6c6549b-8078-4d17-935c-c6db9a370093
fullyQualifiedName: test_pbi.b6c6549b-8078-4d17-935c-c6db9a370093
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/e1a9219d-adf9-48e3-823b-7f2b0a8ac6c0
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 40a428dd7c2ca4e144b7bc4205b97509
dashboards:
  - id: 0dda4b77-b69f-426d-b4ec-7c004db37baa
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: test_pbi.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
