name: ctx_user_index_values
fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values
tableType: View
columns:
  - name: ixv_index_name
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values.ixv_index_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: ixv_class
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values.ixv_class
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ixv_object
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values.ixv_object
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ixv_attribute
    dataType: VARCHAR
    dataLength: 128
    dataTypeDisplay: varchar2(128)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values.ixv_attribute
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ixv_value
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: varchar2(4000)
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_user_index_values.ixv_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5e47000e-823d-436f-9638-5b6ec8cedf56
  type: databaseSchema
  name: ctxsys
  fullyQualifiedName: oracle_test.default.ctxsys
  displayName: ctxsys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: c64722f3b3740f1f1c070532e3f73276
processedLineage: false
entityStatus: Approved
