name: ctx_trace_values
fullyQualifiedName: oracle_test.default.ctxsys.ctx_trace_values
tableType: View
columns:
  - name: trc_id
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_trace_values.trc_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: trc_value
    dataType: NUMBER
    dataLength: 1
    dataTypeDisplay: number
    fullyQualifiedName: oracle_test.default.ctxsys.ctx_trace_values.trc_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5e47000e-823d-436f-9638-5b6ec8cedf56
  type: databaseSchema
  name: ctxsys
  fullyQualifiedName: oracle_test.default.ctxsys
  displayName: ctxsys
  deleted: false
database:
  id: 635299d9-9c3d-4ccc-98ff-dfb95889d8d6
  type: database
  name: default
  fullyQualifiedName: oracle_test.default
  displayName: default
  deleted: false
service:
  id: 81062063-d522-406b-92a3-ccad1f68f1ad
  type: databaseService
  name: oracle_test
  fullyQualifiedName: oracle_test
  displayName: oracle_test
  deleted: false
serviceType: Oracle
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: fda6a0e1fd1d3b0c2e326d81f3647acd
processedLineage: false
entityStatus: Approved
