name: spt_values
fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values
tableType: View
columns:
  - name: name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(35)
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: number
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.number
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: type
    dataType: CHAR
    dataLength: 1
    dataTypeDisplay: nchar(3)
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: low
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.low
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: high
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.high
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: status
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.master.dbo.spt_values.status
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 5e0e1eb7-ae85-47a4-ae3b-ad5cc39c69c8
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.master.dbo
  displayName: dbo
  deleted: false
database:
  id: de2d3569-14e3-4115-838c-1cc71139205e
  type: database
  name: master
  fullyQualifiedName: MSSQL_TEST.master
  displayName: master
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 671ea3ee589aa12bfd130f0f9b984f62
processedLineage: false
entityStatus: Approved
