name: SERVICES
fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES
tableType: View
columns:
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Database that the service belongs to
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Schema that the service belongs to
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: STATUS
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Status of the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.STATUS
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the role that owns the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Type of role that owns the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Name of the compute pool where the service runs
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: DNS name associated with the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CURRENT_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Current number of active instances for the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.CURRENT_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: TARGET_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Target number of active instances for the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.TARGET_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Minimum number of active instances for the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.MIN_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: number
    description: Maximum number of active instances for the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.MAX_INSTANCES
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service can be automatically resumed
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.AUTO_RESUME
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Comment for this service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: Query warehouse of the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Creation time of the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Last altered time of the service
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    description: Time when the service was last resumed
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether this is a Snowpark Container Services Job
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SPEC_DIGEST
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: A unique and immutable identifier to represent the service spec content
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.SPEC_DIGEST
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_UPGRADING
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    description: Whether the service is upgrading or not
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.IS_UPGRADING
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_DOMAIN
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The domain of the managing object
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_DOMAIN
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MANAGING_OBJECT_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    description: The fully qualified name of the managing object
    fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA.SERVICES.MANAGING_OBJECT_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 1a88775c-6050-4098-acf0-9a8d4bd25d45
  type: databaseSchema
  name: INFORMATION_SCHEMA
  fullyQualifiedName: snowflake.TEST_DB.INFORMATION_SCHEMA
  description: Views describing the contents of schemas in this database
  displayName: INFORMATION_SCHEMA
  deleted: false
database:
  id: 2264b2fa-96ab-480d-bb1a-48e2fabb8fcc
  type: database
  name: TEST_DB
  fullyQualifiedName: snowflake.TEST_DB
  displayName: TEST_DB
  deleted: false
service:
  id: ddfc267a-864a-44e0-b26c-82033d85723d
  type: databaseService
  name: snowflake
  fullyQualifiedName: snowflake
  displayName: snowflake
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/qogptxq/gn01172/#/data/databases/TEST_DB/schemas/INFORMATION_SCHEMA/view/SERVICES
domains: []
dataProducts: []
sourceHash: 2b4bee5908c4c20b9d5026633f0329be
processedLineage: false
entityStatus: Approved
