name: FiscalYearSettings
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Fiscal Year Settings ID
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: PeriodId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Period ID
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.PeriodId
    tags: []
    constraint: "NULL"
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: StartDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: date
    description: Start Date
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.StartDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: EndDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: date
    description: End Date
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.EndDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.Name
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: IsStandardYear
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Is Standard Year
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.IsStandardYear
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: YearType
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Year Type
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.YearType
    tags: []
    constraint: "NULL"
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: QuarterLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Quarter Name Scheme
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.QuarterLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: PeriodLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Period Name Scheme
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.PeriodLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: WeekLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Week Name Scheme
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.WeekLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: QuarterPrefix
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Quarter Prefix
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.QuarterPrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: PeriodPrefix
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Period Prefix
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.PeriodPrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: WeekStartDay
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: Week Start Day
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.WeekStartDay
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: Description
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Description
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.Description
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.FiscalYearSettings.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 15
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620844222
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/FiscalYearSettings/list
domains: []
dataProducts: []
sourceHash: e1d43a6d0d469974d44ea2bea23da07c
processedLineage: false
entityStatus: Approved
