name: MobileApplicationDetail
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Mobile Application Detail Id
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: DeveloperName
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.DeveloperName
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Language
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Master Language
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.Language
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: MasterLabel
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Master Label
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.MasterLabel
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: NamespacePrefix
    dataType: UNKNOWN
    dataLength: 15
    dataTypeDisplay: string
    description: Namespace Prefix
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.NamespacePrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: Version
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Version
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.Version
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: DevicePlatform
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Device Platform
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.DevicePlatform
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: MinimumOsVersion
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Minimum OS Version
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.MinimumOsVersion
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: DeviceType
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Device Type
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.DeviceType
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: ApplicationFileLength
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: Application File Length
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationFileLength
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: ApplicationIcon
    dataType: VARCHAR
    dataLength: 32768
    dataTypeDisplay: textarea
    description: Application Icon
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationIcon
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: IsEnterpriseApp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Enterprise Application
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.IsEnterpriseApp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: AppInstallUrl
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: url
    description: Installation URL
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.AppInstallUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 19
    children: []
    customMetrics: []
  - name: ApplicationBundleIdentifier
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Application Bundle Identifier
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationBundleIdentifier
    tags: []
    constraint: "NULL"
    ordinalPosition: 20
    children: []
    customMetrics: []
  - name: ApplicationBinaryFileName
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Application Binary File Name
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationBinaryFileName
    tags: []
    constraint: "NULL"
    ordinalPosition: 21
    children: []
    customMetrics: []
  - name: ApplicationIconFileName
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Application Icon File Name
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationIconFileName
    tags: []
    constraint: "NULL"
    ordinalPosition: 22
    children: []
    customMetrics: []
  - name: ApplicationBinary
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: base64
    description: Application Binary
    fullyQualifiedName: demo_salesforce.default.salesforce.MobileApplicationDetail.ApplicationBinary
    tags: []
    constraint: "NULL"
    ordinalPosition: 23
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620857155
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/MobileApplicationDetail/list
domains: []
dataProducts: []
sourceHash: 80a448afd466402594ce1d8782a427e9
processedLineage: false
entityStatus: Approved
