name: SamlSsoConfig
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: SAML Single Sign-On Setting ID
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: DeveloperName
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.DeveloperName
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Language
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Master Language
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.Language
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: MasterLabel
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Label
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.MasterLabel
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: NamespacePrefix
    dataType: UNKNOWN
    dataLength: 15
    dataTypeDisplay: string
    description: Namespace Prefix
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.NamespacePrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: Version
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Version
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.Version
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: Issuer
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Issuer
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.Issuer
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: OptionsSpInitBinding
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: SpInitBinding
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.OptionsSpInitBinding
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: OptionsUserProvisioning
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: UserProvisioning
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.OptionsUserProvisioning
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: AttributeFormat
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Name ID Format
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.AttributeFormat
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: AttributeName
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Attribute Name
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.AttributeName
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: Audience
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Entity ID
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.Audience
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: IdentityMapping
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Identity Type
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.IdentityMapping
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 19
    children: []
    customMetrics: []
  - name: IdentityLocation
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: SAML Identity Location
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.IdentityLocation
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 20
    children: []
    customMetrics: []
  - name: ExecutionUserId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: User ID
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.ExecutionUserId
    tags: []
    constraint: "NULL"
    ordinalPosition: 21
    children: []
    customMetrics: []
  - name: LoginUrl
    dataType: UNKNOWN
    dataLength: 1500
    dataTypeDisplay: string
    description: Identity Provider Login URL
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.LoginUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 22
    children: []
    customMetrics: []
  - name: LogoutUrl
    dataType: UNKNOWN
    dataLength: 1500
    dataTypeDisplay: string
    description: Identity Provider Logout URL
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.LogoutUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 23
    children: []
    customMetrics: []
  - name: ErrorUrl
    dataType: UNKNOWN
    dataLength: 500
    dataTypeDisplay: string
    description: Custom Error URL
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.ErrorUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 24
    children: []
    customMetrics: []
  - name: ValidationCert
    dataType: UNKNOWN
    dataLength: 4000
    dataTypeDisplay: string
    description: Identity Provider Certificate
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.ValidationCert
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 25
    children: []
    customMetrics: []
  - name: RequestSignatureMethod
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Request Signature Method
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.RequestSignatureMethod
    tags: []
    constraint: "NULL"
    ordinalPosition: 26
    children: []
    customMetrics: []
  - name: SingleLogoutUrl
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Identity Provider Single Logout URL
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.SingleLogoutUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 27
    children: []
    customMetrics: []
  - name: SingleLogoutBinding
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Single Logout Request Binding
    fullyQualifiedName: demo_salesforce.default.salesforce.SamlSsoConfig.SingleLogoutBinding
    tags: []
    constraint: "NULL"
    ordinalPosition: 28
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620873995
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/SamlSsoConfig/list
domains: []
dataProducts: []
sourceHash: 7789e7de80f5cd805276dafd3bbd1a2d
processedLineage: false
entityStatus: Approved
