name: UserProvisioningConfig
displayName: ""
fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig
description: ""
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: UserProvisioningConfig ID
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: DeveloperName
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.DeveloperName
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Language
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Master Language
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.Language
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: MasterLabel
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Label
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.MasterLabel
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: NamespacePrefix
    dataType: UNKNOWN
    dataLength: 15
    dataTypeDisplay: string
    description: Namespace Prefix
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.NamespacePrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: ConnectedAppId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Connected App ID
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.ConnectedAppId
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: Notes
    dataType: VARCHAR
    dataLength: 65536
    dataTypeDisplay: textarea
    description: Notes
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.Notes
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: Enabled
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Enabled
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.Enabled
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: ApprovalRequired
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: textarea
    description: Approval Required
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.ApprovalRequired
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: UserAccountMapping
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: textarea
    description: User Account Mapping
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.UserAccountMapping
    tags: []
    constraint: "NULL"
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: EnabledOperations
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: textarea
    description: Enabled Operations
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.EnabledOperations
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: OnUpdateAttributes
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: textarea
    description: On Update Attributes
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.OnUpdateAttributes
    tags: []
    constraint: "NULL"
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: LastReconDateTime
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Recon Date
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.LastReconDateTime
    tags: []
    constraint: "NULL"
    ordinalPosition: 19
    children: []
    customMetrics: []
  - name: NamedCredentialId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Named Credential ID
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.NamedCredentialId
    tags: []
    constraint: "NULL"
    ordinalPosition: 20
    children: []
    customMetrics: []
  - name: ReconFilter
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Recon Filter
    fullyQualifiedName: demo_salesforce.default.salesforce.UserProvisioningConfig.ReconFilter
    tags: []
    constraint: "NULL"
    ordinalPosition: 21
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 577faa78-100e-43dc-87e4-cf005ab3440b
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: demo_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: a01977c7-839c-43d2-833e-0c7d06be0cdc
  type: database
  name: default
  fullyQualifiedName: demo_salesforce.default
  displayName: default
  deleted: false
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: description
      newValue: ""
    - name: displayName
      newValue: ""
    - name: retentionPeriod
      newValue: ""
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary:
    description:
      changedBy: ashish
      changedAt: 1741620885935
retentionPeriod: ""
sourceUrl: https://innovation-force-7398.my.salesforce.com/lightning/o/UserProvisioningConfig/list
domains: []
dataProducts: []
sourceHash: 6dc5230bcc78186086f187adf4143be8
processedLineage: false
entityStatus: Approved
