name: distributed_cache_client_settings
fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings
description: "A system table, which allows to see distributed cache clients settings."
tableType: Regular
columns:
  - name: client_id
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Distributed Cache client id
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.client_id
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: client_weight
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache client weight.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.client_weight
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: secure
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: Whether secure connection is being used.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.secure
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: connection_pool_size
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache connection pool size.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.connection_pool_size
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: connection_pool_connection_ttl_sec
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: TTL for distributed cache connection residing in connection pool
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.connection_pool_connection_ttl_sec
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: max_packet_size
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache max packet size for `DataPacket`.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.max_packet_size
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: max_virtual_nodes_in_hash_ring
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache number of virtual nodes in a hash ring.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.max_virtual_nodes_in_hash_ring
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: offset_alignment
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache offset alignment.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.offset_alignment
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: local
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: Whether local (testing) mode is on.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.local
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: registry_watch_wait_timeout_milliseconds
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: uint64
    description: Distributed Cache Registry timeout to watch registered cache servers.
    fullyQualifiedName: test_clickhouse.default.system.distributed_cache_client_settings.registry_watch_wait_timeout_milliseconds
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 8a7299bd-4233-40a1-9e70-dc760e5e6b42
  type: databaseSchema
  name: system
  fullyQualifiedName: test_clickhouse.default.system
  displayName: system
  deleted: false
database:
  id: 892667da-43ed-425c-94ad-24a4cc252df4
  type: database
  name: default
  fullyQualifiedName: test_clickhouse.default
  displayName: default
  deleted: false
service:
  id: b468f00e-0925-45e5-a89d-c038e1a5e79f
  type: databaseService
  name: test_clickhouse
  fullyQualifiedName: test_clickhouse
  description: ""
  displayName: test_clickhouse
  deleted: false
serviceType: Clickhouse
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: fe851361e0160d5401a5aa83d66fffdb
processedLineage: false
entityStatus: Unprocessed
