name: s3_queue_settings
fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings
description: Contains a list of settings of S3Queue tables.
tableType: Regular
columns:
  - name: database
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Database of the table with S3Queue Engine.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.database
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: table
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Name of the table with S3Queue Engine.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.table
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Setting name.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: value
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Setting value.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.value
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: type
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Setting type (implementation specific string value).
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.type
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: changed
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: 1 if the setting was explicitly defined in the config or explicitly
      changed.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.changed
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: description
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Setting description.
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.description
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: alterable
    dataType: SMALLINT
    dataLength: 1
    dataTypeDisplay: uint8
    description: "Shows whether the current user can change the setting via ALTER\
      \ TABLE MODIFY SETTING: 0 — Current user can change the setting, 1 — Current\
      \ user can't change the setting."
    fullyQualifiedName: test_clickhouse.default.system.s3_queue_settings.alterable
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 8a7299bd-4233-40a1-9e70-dc760e5e6b42
  type: databaseSchema
  name: system
  fullyQualifiedName: test_clickhouse.default.system
  displayName: system
  deleted: false
database:
  id: 892667da-43ed-425c-94ad-24a4cc252df4
  type: database
  name: default
  fullyQualifiedName: test_clickhouse.default
  displayName: default
  deleted: false
service:
  id: b468f00e-0925-45e5-a89d-c038e1a5e79f
  type: databaseService
  name: test_clickhouse
  fullyQualifiedName: test_clickhouse
  description: ""
  displayName: test_clickhouse
  deleted: false
serviceType: Clickhouse
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 4beb2635e591233288045dfd6ea3028f
processedLineage: false
entityStatus: Unprocessed
