name: 1
displayName: Untitled
fullyQualifiedName: local_looker.1
chartType: Other
sourceUrl: https://collate.cloud.looker.com/x/CKBk06gIf0yz30eBCDZJVE
owners: []
tags: []
service:
  id: 2701de85-0e6a-41ef-9f2a-80bff831017c
  type: dashboardService
  name: local_looker
  fullyQualifiedName: local_looker
  displayName: local_looker
  deleted: false
serviceType: Looker
domains: []
dataProducts: []
sourceHash: f8acdc16ef5d36e3cc79d0f666571149
dashboards:
  - id: b8aeb322-69ad-4122-b3d1-91444886d83d
    type: dashboard
    name: 1
    fullyQualifiedName: local_looker.1
    displayName: customers dashboard
    deleted: false
entityStatus: Unprocessed
