name: 2
displayName: users age
fullyQualifiedName: local_looker.2
chartType: Other
sourceUrl: https://collate.cloud.looker.com/x/yfYyLIrV7fFgtaEdBUAxYj
owners: []
tags: []
service:
  id: 2701de85-0e6a-41ef-9f2a-80bff831017c
  type: dashboardService
  name: local_looker
  fullyQualifiedName: local_looker
  displayName: local_looker
  deleted: false
serviceType: Looker
domains: []
dataProducts: []
sourceHash: 29b56a58d091bf637b5907778388cbfb
dashboards:
  - id: b1ebf1df-14e7-4176-8690-32546216a146
    type: dashboard
    name: 2
    fullyQualifiedName: local_looker.2
    displayName: users
    deleted: false
entityStatus: Unprocessed
