name: WDAD5191D7DFB4B19A1B04E3420B2BB80K0B2DB270324390B6C80074AE1EECBEAD
displayName: Clients
fullyQualifiedName: microstrategy_service.WDAD5191D7DFB4B19A1B04E3420B2BB80K0B2DB270324390B6C80074AE1EECBEAD
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 385f71ed657885268c175ee9cc951e4e
dashboards:
  - id: c7960565-1f6e-4281-a9e8-e8344f4ed6e5
    type: dashboard
    name: 003B0F1DC044BCCC006025A2C0D0B06A
    fullyQualifiedName: microstrategy_service.003B0F1DC044BCCC006025A2C0D0B06A
    displayName: Finance Wealth Management
    deleted: false
entityStatus: Approved
