name: WC1FBED72B3B640DCB7E5409822DFE310W48953F5226C9461FB5728A6BD6BA3986
displayName: In general do you think our economy is on the right track or is it off
  on the wrong track? copy
fullyQualifiedName: microstrategy_service.WC1FBED72B3B640DCB7E5409822DFE310W48953F5226C9461FB5728A6BD6BA3986
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 3ce6b6cff8d982fcc2ca6668eef7b72e
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
