name: WB9739EB430D94C3D8AB3A26CD742C1ABW2AD5469DF3974E29BAE1DDC3C94F9194
displayName: Points Per Game
fullyQualifiedName: microstrategy_service.WB9739EB430D94C3D8AB3A26CD742C1ABW2AD5469DF3974E29BAE1DDC3C94F9194
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 11762410b5a8e94d8940348e204e13c7
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
