name: K53W26BB20971E7444C89855C9B1BA7E443B
displayName: Correlation Customer Satisfaction and Units Sold Break by Customer
fullyQualifiedName: microstrategy_service.K53W26BB20971E7444C89855C9B1BA7E443B
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: d73be20da567cfab0de1a8cc28dd46b8
dashboards:
  - id: d97fbc81-90f9-4466-a753-9f5be3daca14
    type: dashboard
    name: 2154CA4B3544FE8F24F288B39A00BC9C
    fullyQualifiedName: microstrategy_service.2154CA4B3544FE8F24F288B39A00BC9C
    displayName: Tec Coffee Quick Insights_lastversionWithHTMLContainer
    deleted: false
entityStatus: Approved
