name: WB9739EB430D94C3D8AB3A26CD742C1ABW49CF4F2D66ED4E94A2EDE1EECF7FD5AD
displayName: Top Players by Season Total Metrics
fullyQualifiedName: microstrategy_service.WB9739EB430D94C3D8AB3A26CD742C1ABW49CF4F2D66ED4E94A2EDE1EECF7FD5AD
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: a483328a14b8f82926168d25742ced7c
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
