name: W11A99D5B4D924ABAB990230D8D6F4E9AK118BD3C5B7483230D0CB2BBDE3EA9A06
displayName: 'Cluster Segmentation by Zip Code '
fullyQualifiedName: microstrategy_service.W11A99D5B4D924ABAB990230D8D6F4E9AK118BD3C5B7483230D0CB2BBDE3EA9A06
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: dea33f8b44cfa0ffb6898e2622ae8016
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
