name: W03DD3A681636454E94C25912B61BE609W87E15F5A47FC435E90E4B5045C34337D
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.W03DD3A681636454E94C25912B61BE609W87E15F5A47FC435E90E4B5045C34337D
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 237fc7dd2079e045fc6a32d0b2e70cd6
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
