name: WBF42D99E3AF4490B8DF31865C8B483F1WDAA81451CA1B4D1184235E8EAB3C98B8
displayName: Ring Chart
fullyQualifiedName: microstrategy_service.WBF42D99E3AF4490B8DF31865C8B483F1WDAA81451CA1B4D1184235E8EAB3C98B8
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: f070309344c09f3e8c7ee463b855d0d1
dashboards:
  - id: 69b96b32-9865-4332-9a29-9d3814683eb0
    type: dashboard
    name: 965451BD2347586FBC9B158D1C305FA0
    fullyQualifiedName: microstrategy_service.965451BD2347586FBC9B158D1C305FA0
    displayName: Custom SVG Visualizations
    deleted: false
entityStatus: Approved
