name: KF77EB66C11E95639C2B50080EF956C21WF052D7D622E140F58C1112ACFC2D8CE0
displayName: Rebounds Per Game
fullyQualifiedName: microstrategy_service.KF77EB66C11E95639C2B50080EF956C21WF052D7D622E140F58C1112ACFC2D8CE0
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 2907c17cba00dcdd25823839fe50cd1b
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
