name: cf0bf684-0a07-4b54-94e8-0b0b55b3035c
displayName: Random Sheet
fullyQualifiedName: Tableau.cf0bf684-0a07-4b54-94e8-0b0b55b3035c
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/TestWorkbook/RandomSheet
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 50d19ac4c8932c91521e0dcc395a7aca
dashboards:
  - id: 25ecebc7-2f44-49d4-b620-1315706d7bb7
    type: dashboard
    name: 6df8deaf-c4f1-4ffd-b1bf-dec9c9515038
    fullyQualifiedName: Tableau.6df8deaf-c4f1-4ffd-b1bf-dec9c9515038
    displayName: Test Workbook
    deleted: false
entityStatus: Approved
