name: 5bd279cb-5802-4f3a-a8a5-451ae6bbcf6e
displayName: Care Spend
fullyQualifiedName: Tableau.5bd279cb-5802-4f3a-a8a5-451ae6bbcf6e
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/WorldIndicators/CareSpend
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: f05fa252cd49d5ddc6b4e7dd3ca9ce24
dashboards:
  - id: 0f8e11d2-f2b2-4f90-bf7c-292685d660f4
    type: dashboard
    name: c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    fullyQualifiedName: Tableau.c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    displayName: World Indicators
    deleted: false
entityStatus: Approved
