name: 4e3970a4-3f3d-4539-a5f9-abb57679e5e6
displayName: omone
fullyQualifiedName: test_pbi.4e3970a4-3f3d-4539-a5f9-abb57679e5e6
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/reports/c771ab29-5792-46fc-9eaa-f86d48e63577
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 4ec41cb80754585289f0425202f98c55
dashboards:
  - id: 0cf58dcc-441d-4185-96c1-e4aac7701377
    type: dashboard
    name: f04bc883-f554-4d16-b0b6-96ec49090bda
    fullyQualifiedName: test_pbi.f04bc883-f554-4d16-b0b6-96ec49090bda
    displayName: OM One dashboard
    deleted: false
entityStatus: Approved
