name: ed448e70-9cbe-49e7-be7a-dc3da358bc45
displayName: ed448e70-9cbe-49e7-be7a-dc3da358bc45
fullyQualifiedName: test_pbi.ed448e70-9cbe-49e7-be7a-dc3da358bc45
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/reports/0d04b324-2ee4-4f49-baa4-8bf88c33cf80
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: e15dbfce77751d9525f6d115e05e8d4d
dashboards:
  - id: 53394e37-6595-4544-816f-8846721ea07f
    type: dashboard
    name: 87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    fullyQualifiedName: test_pbi.87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    displayName: Human Resources Sample
    deleted: false
entityStatus: Approved
