name: 3e79e403-2b3e-4209-8ac6-67cdf013a532
displayName: Product Measure Sheet
fullyQualifiedName: Test_tableau.3e79e403-2b3e-4209-8ac6-67cdf013a532
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AnalyticsWorkbook/ProductMeasureSheet
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: ec09fd31d69e3e17d5f75d3a8e78d03f
dashboards:
  - id: 62c8bad7-d60c-4e3e-a143-79832b03b129
    type: dashboard
    name: 6c602fd5-7a2c-4af5-881f-165d734c4169
    fullyQualifiedName: Test_tableau.6c602fd5-7a2c-4af5-881f-165d734c4169
    displayName: Analytics Workbook
    deleted: false
entityStatus: Approved
