name: d762fed7-a604-4728-9030-7feb672991b2
displayName: d762fed7-a604-4728-9030-7feb672991b2
fullyQualifiedName: test_pbi.d762fed7-a604-4728-9030-7feb672991b2
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/e1a9219d-adf9-48e3-823b-7f2b0a8ac6c0
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: fcce6f876ebf2706d9035918cc82d3d1
dashboards:
  - id: 0dda4b77-b69f-426d-b4ec-7c004db37baa
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: test_pbi.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
