name: 29210a49-deb8-44b6-9c40-545ae0a42b8b
displayName: lineagetest2work
fullyQualifiedName: test_pbi.29210a49-deb8-44b6-9c40-545ae0a42b8b
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/5c2bd38b-6980-44c5-9a81-7b3d51714155
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: b854171202411b83a994dbcf0be4a902
dashboards:
  - id: 5331d4db-9c80-4e5d-a09a-5eec3b93b318
    type: dashboard
    name: d142fcb5-0370-4421-bebf-3ace1c03cf75
    fullyQualifiedName: test_pbi.d142fcb5-0370-4421-bebf-3ace1c03cf75
    displayName: Lineage testing dashboard
    deleted: false
entityStatus: Approved
