name: 312dc4c2-7360-4e7c-ae8b-4da6e3102ae5
displayName: Tourism
fullyQualifiedName: Test_tableau.312dc4c2-7360-4e7c-ae8b-4da6e3102ae5
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/Tourism
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 54c742ab454812dd801330c6956eb0b0
dashboards:
  - id: 1678d28a-92e8-420e-91de-13037e162c76
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: Test_tableau.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Approved
