name: 8cd9eb3d-fd51-4514-a015-a73ef711a3a1
displayName: 8cd9eb3d-fd51-4514-a015-a73ef711a3a1
fullyQualifiedName: test_pbi.8cd9eb3d-fd51-4514-a015-a73ef711a3a1
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/d7d155f1-1b8c-49dc-90cd-da4b1c81fd54
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: dfa0f2c4b16f1afab32590b23fdca12d
dashboards:
  - id: 44101b1b-96d8-43fd-9081-948e252380fb
    type: dashboard
    name: 70fa3baf-6e21-419e-832d-60a418a0cdd0
    fullyQualifiedName: test_pbi.70fa3baf-6e21-419e-832d-60a418a0cdd0
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
