name: bcd43597-b84d-42b2-98b7-298a5517d27e
displayName: bcd43597-b84d-42b2-98b7-298a5517d27e
fullyQualifiedName: test_pbi.bcd43597-b84d-42b2-98b7-298a5517d27e
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/06808307-e9b1-4661-8671-9866ad4e81b1
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: fd869b57ea682129e9297b12afcfc5a8
dashboards:
  - id: 583413ff-daad-4d8c-afa3-d21556b747a4
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: test_pbi.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
entityStatus: Approved
