name: autoadmin_backup_configuration_summary
fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary
tableType: View
columns:
  - name: ManagedBackupVersion
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.ManagedBackupVersion
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: IsAlwaysOn
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.IsAlwaysOn
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IsDropped
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.IsDropped
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IsEnabled
    dataType: BIT
    dataLength: 1
    dataTypeDisplay: bit
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.IsEnabled
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: RetentionPeriod
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.RetentionPeriod
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: EncryptionAlgorithm
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.EncryptionAlgorithm
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SchedulingOption
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.SchedulingOption
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DayOfWeek
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(256)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.DayOfWeek
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DatabaseCount
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.autoadmin_backup_configuration_summary.DatabaseCount
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 57c2f396-9b05-4e00-9903-62b0219fbc25
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: af8db866-dbb4-4bd5-a2ea-22202fbc71ef
  type: database
  name: msdb
  fullyQualifiedName: MSSQL_TEST.msdb
  displayName: msdb
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: d2d852c9af94c67c74c21d4def5b8508
processedLineage: false
entityStatus: Approved
