name: syscollector_config_store
fullyQualifiedName: MSSQL_TEST.msdb.dbo.syscollector_config_store
tableType: View
columns:
  - name: parameter_name
    dataType: VARCHAR
    dataLength: 1
    dataTypeDisplay: nvarchar(128)
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.syscollector_config_store.parameter_name
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
  - name: parameter_value
    dataType: VARBINARY
    dataLength: 1
    dataTypeDisplay: sql_variant
    fullyQualifiedName: MSSQL_TEST.msdb.dbo.syscollector_config_store.parameter_value
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 57c2f396-9b05-4e00-9903-62b0219fbc25
  type: databaseSchema
  name: dbo
  fullyQualifiedName: MSSQL_TEST.msdb.dbo
  displayName: dbo
  deleted: false
database:
  id: af8db866-dbb4-4bd5-a2ea-22202fbc71ef
  type: database
  name: msdb
  fullyQualifiedName: MSSQL_TEST.msdb
  displayName: msdb
  deleted: false
service:
  id: 1ef4c8da-1280-42c0-8b83-142c3a019de7
  type: databaseService
  name: MSSQL_TEST
  fullyQualifiedName: MSSQL_TEST
  description: ""
  displayName: MSSQL_TEST
  deleted: false
serviceType: Mssql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: aef8700f682e0a6dbd45e9ae1cb2dcbe
processedLineage: false
entityStatus: Approved
