name: accepted_values_marketing_attr_bc022655dc12a6a681ec3b39dafc10cb
fullyQualifiedName: red-pere.dev.dbt_test_marketing_dbt_test__audit.accepted_values_marketing_attr_bc022655dc12a6a681ec3b39dafc10cb
tableType: Regular
columns:
  - name: value_field
    dataType: VARCHAR
    dataLength: 19
    dataTypeDisplay: character varying(19)
    fullyQualifiedName: red-pere.dev.dbt_test_marketing_dbt_test__audit.accepted_values_marketing_attr_bc022655dc12a6a681ec3b39dafc10cb.value_field
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: n_records
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    fullyQualifiedName: red-pere.dev.dbt_test_marketing_dbt_test__audit.accepted_values_marketing_attr_bc022655dc12a6a681ec3b39dafc10cb.n_records
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: DIST_KEY
    columns:
      - value_field
owners: []
databaseSchema:
  id: 683f7b46-f832-42ef-8b9b-00b824858a32
  type: databaseSchema
  name: dbt_test_marketing_dbt_test__audit
  fullyQualifiedName: red-pere.dev.dbt_test_marketing_dbt_test__audit
  displayName: dbt_test_marketing_dbt_test__audit
  deleted: false
database:
  id: 2da3a66d-ee52-4772-a36b-33235bd5fd46
  type: database
  name: dev
  fullyQualifiedName: red-pere.dev
  displayName: dev
  deleted: false
service:
  id: 0161f1c0-0881-4409-8387-85521aa692e3
  type: databaseService
  name: red-pere
  fullyQualifiedName: red-pere
  displayName: red-pere
  deleted: false
serviceType: Redshift
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 2f3bf7b1dad8c26286137a5e3b0d87db
processedLineage: false
entityStatus: Unprocessed
