name: FiscalYearSettings
fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings
description: Fiscal Year Settings
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Fiscal Year Settings ID
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: PeriodId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Period ID
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.PeriodId
    tags: []
    constraint: "NULL"
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: StartDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: date
    description: Start Date
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.StartDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: EndDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: date
    description: End Date
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.EndDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 80
    dataTypeDisplay: string
    description: Name
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.Name
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: IsStandardYear
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Is Standard Year
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.IsStandardYear
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: YearType
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Year Type
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.YearType
    tags: []
    constraint: "NULL"
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: QuarterLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Quarter Name Scheme
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.QuarterLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: PeriodLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Period Name Scheme
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.PeriodLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: WeekLabelScheme
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Week Name Scheme
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.WeekLabelScheme
    tags: []
    constraint: "NULL"
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: QuarterPrefix
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Quarter Prefix
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.QuarterPrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: PeriodPrefix
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Period Prefix
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.PeriodPrefix
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: WeekStartDay
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: int
    description: Week Start Day
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.WeekStartDay
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: Description
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Description
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.Description
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.FiscalYearSettings.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 15
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/FiscalYearSettings/list
domains: []
dataProducts: []
sourceHash: e75f777502697a2fe9ac211dcf71a60e
processedLineage: false
entityStatus: Unprocessed
