name: SERVICES
fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES
tableType: View
columns:
  - name: SERVICE_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_SCHEMA_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_SCHEMA
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_SCHEMA
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_CATALOG_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_CATALOG_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_CATALOG
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_CATALOG
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_OWNER
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_OWNER
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: SERVICE_OWNER_ROLE_TYPE
    dataType: VARCHAR
    dataLength: 13
    dataTypeDisplay: text(13)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.SERVICE_OWNER_ROLE_TYPE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_ID
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMPUTE_POOL_ID
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMPUTE_POOL_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMPUTE_POOL_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DNS_NAME
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.DNS_NAME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MIN_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.MIN_INSTANCES
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: MAX_INSTANCES
    dataType: DECIMAL
    dataLength: 1
    precision: 38
    scale: 0
    dataTypeDisplay: "number(38,0)"
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.MAX_INSTANCES
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: AUTO_RESUME
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.AUTO_RESUME
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: COMMENT
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.COMMENT
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: QUERY_WAREHOUSE
    dataType: VARCHAR
    dataLength: 16777216
    dataTypeDisplay: text(16777216)
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.QUERY_WAREHOUSE
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CREATED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.CREATED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_ALTERED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.LAST_ALTERED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: LAST_RESUMED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.LAST_RESUMED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DELETED
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp_ltz
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.DELETED
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: IS_JOB
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE.SERVICES.IS_JOB
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 865bc079-eb8c-4684-be2b-8ffd6081f248
  type: databaseSchema
  name: ACCOUNT_USAGE
  fullyQualifiedName: snowflaketest2.SNOWFLAKE.ACCOUNT_USAGE
  displayName: ACCOUNT_USAGE
  deleted: false
database:
  id: 7e1d2fd6-f313-40f5-9bb5-73cc4181dd6b
  type: database
  name: SNOWFLAKE
  fullyQualifiedName: snowflaketest2.SNOWFLAKE
  displayName: SNOWFLAKE
  deleted: false
service:
  id: 6eae98d4-b082-407b-ac68-8864158c3427
  type: databaseService
  name: snowflaketest2
  fullyQualifiedName: snowflaketest2
  displayName: snowflaketest2
  deleted: false
serviceType: Snowflake
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
sourceUrl: https://app.snowflake.com/qogptxq/gn01172/#/data/databases/SNOWFLAKE/schemas/ACCOUNT_USAGE/view/SERVICES
domains: []
dataProducts: []
sourceHash: 6ec97ed71a03b4b886d66f59e0069405
processedLineage: false
entityStatus: Approved
