name: FLW_EVENT_DEPLOYMENT
fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT
tableType: Regular
columns:
  - name: ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.ID_
    tags: []
    constraint: PRIMARY_KEY
    children: []
    customMetrics: []
  - name: NAME_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.NAME_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: CATEGORY_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.CATEGORY_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: DEPLOY_TIME_
    dataType: DATETIME
    dataLength: 1
    dataTypeDisplay: datetime
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.DEPLOY_TIME_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: TENANT_ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.TENANT_ID_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: PARENT_DEPLOYMENT_ID_
    dataType: VARCHAR
    dataLength: 255
    dataTypeDisplay: varchar(255)
    fullyQualifiedName: Gyo2.default.openmetadata_db.FLW_EVENT_DEPLOYMENT.PARENT_DEPLOYMENT_ID_
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 1ae3a711-6b03-48cc-a7de-9a34be516eab
  type: databaseSchema
  name: openmetadata_db
  fullyQualifiedName: Gyo2.default.openmetadata_db
  displayName: openmetadata_db
  deleted: false
database:
  id: b43ed889-df08-430d-8b37-2ee890216f2a
  type: database
  name: default
  fullyQualifiedName: Gyo2.default
  displayName: default
  deleted: false
service:
  id: acb4d7cc-507e-43a0-b287-0127da7c758d
  type: databaseService
  name: Gyo2
  fullyQualifiedName: Gyo2
  description: ""
  displayName: Gyo2
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 460683f8a5ce8ae533a0d62d60c6d822
processedLineage: false
entityStatus: Approved
