name: openmetadata_settings
fullyQualifiedName: Gyo2.default.openmetadata_db.openmetadata_settings
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: mediumint
    fullyQualifiedName: Gyo2.default.openmetadata_db.openmetadata_settings.id
    tags: []
    children: []
    customMetrics: []
  - name: configType
    dataType: VARCHAR
    dataLength: 36
    dataTypeDisplay: varchar(36)
    fullyQualifiedName: Gyo2.default.openmetadata_db.openmetadata_settings.configType
    tags: []
    children: []
    customMetrics: []
  - name: json
    dataType: JSON
    dataLength: 1
    dataTypeDisplay: json
    fullyQualifiedName: Gyo2.default.openmetadata_db.openmetadata_settings.json
    tags: []
    constraint: NOT_NULL
    children: []
    customMetrics: []
tableConstraints:
  - constraintType: PRIMARY_KEY
    columns:
      - id
      - configType
owners: []
databaseSchema:
  id: 1ae3a711-6b03-48cc-a7de-9a34be516eab
  type: databaseSchema
  name: openmetadata_db
  fullyQualifiedName: Gyo2.default.openmetadata_db
  displayName: openmetadata_db
  deleted: false
database:
  id: b43ed889-df08-430d-8b37-2ee890216f2a
  type: database
  name: default
  fullyQualifiedName: Gyo2.default
  displayName: default
  deleted: false
service:
  id: acb4d7cc-507e-43a0-b287-0127da7c758d
  type: databaseService
  name: Gyo2
  fullyQualifiedName: Gyo2
  description: ""
  displayName: Gyo2
  deleted: false
serviceType: Mysql
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: e746ac3bcbe73efc1a4f6f39bd9678d3
processedLineage: false
entityStatus: Approved
