name: WE412F40F1DB347E9AFF482A087F3D158WE1C52E027B124788B3C83F19FB406999
displayName: Top Players Across the Globe
fullyQualifiedName: microstrategy_service.WE412F40F1DB347E9AFF482A087F3D158WE1C52E027B124788B3C83F19FB406999
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 5622b82c4e9c7fd4ab917c5a840aba74
dashboards:
  - id: 585cc44c-3ace-45ac-a507-102a36919ca0
    type: dashboard
    name: 59AB0AB411E95628C2B50080EF156C20
    fullyQualifiedName: microstrategy_service.59AB0AB411E95628C2B50080EF156C20
    displayName: March Madness 2019
    deleted: false
entityStatus: Approved
