name: WE4D8A639C04B4CAB900AC5C80726C783WB9A69B6D12204500ACF705B504DDFBC9
displayName: Visualization 3 copy
fullyQualifiedName: microstrategy_service.WE4D8A639C04B4CAB900AC5C80726C783WB9A69B6D12204500ACF705B504DDFBC9
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: b44515f5d23cba918904f16804fc916d
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
