name: 637302c3-624e-458d-a428-53a0bd3dad60
displayName: 637302c3-624e-458d-a428-53a0bd3dad60
fullyQualifiedName: powerbi_prod.637302c3-624e-458d-a428-53a0bd3dad60
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/reports/0d04b324-2ee4-4f49-baa4-8bf88c33cf80
owners: []
tags: []
service:
  id: 89d9de05-72fb-4da7-9066-4f8c202000ea
  type: dashboardService
  name: powerbi_prod
  fullyQualifiedName: powerbi_prod
  description: ""
  displayName: powerbi_prod
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: e4f91e6d9521756ba054e237d72aa03a
dashboards:
  - id: bf7d0006-747d-4147-8fe3-b8b5a5b9cbbc
    type: dashboard
    name: 10b5fb06-2bc0-4634-9b56-f6edf9cddc50
    fullyQualifiedName: powerbi_prod.10b5fb06-2bc0-4634-9b56-f6edf9cddc50
    displayName: products dashboard
    deleted: false
  - id: 80e9acd7-3382-4fc7-a7a7-d91cf8a3a4cf
    type: dashboard
    name: 4590880a-70e0-482f-8e10-480a3999b165
    fullyQualifiedName: powerbi_prod.4590880a-70e0-482f-8e10-480a3999b165
    displayName: Lineage Test 1 Dashboard
    deleted: false
  - id: ef8608a0-34ef-4793-86c2-a54d9395e5b2
    type: dashboard
    name: 87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    fullyQualifiedName: powerbi_prod.87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    displayName: Human Resources Sample
    deleted: false
  - id: 6da05150-9e60-4426-a4ec-5ac806493a66
    type: dashboard
    name: f04bc883-f554-4d16-b0b6-96ec49090bda
    fullyQualifiedName: powerbi_prod.f04bc883-f554-4d16-b0b6-96ec49090bda
    displayName: OM One dashboard
    deleted: false
entityStatus: Approved
