name: 170
displayName: Box plot
fullyQualifiedName: sample_superset.170
description: ""
chartType: Bar
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20170%7D
owners: []
tags: []
service:
  id: 8db95335-b86e-476f-b5c6-39c029d866ff
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted:
    - name: dashboards
      oldValue: "[{\"id\":\"432eefd2-1e7c-46fd-916a-7cd7fbe410f8\",\"type\":\"dashboard\"\
        ,\"name\":\"11\",\"fullyQualifiedName\":\"sample_superset.11\",\"description\"\
        :\"\",\"displayName\":\"FCC New Coder Survey 2018\",\"deleted\":false},{\"\
        id\":\"4564d142-6f2f-4a7c-8ff4-2d6397b82d06\",\"type\":\"dashboard\",\"name\"\
        :\"34\",\"fullyQualifiedName\":\"sample_superset.34\",\"description\":\"\"\
        ,\"displayName\":\"Unicode Test\",\"deleted\":false},{\"id\":\"1a7bac61-6887-4614-8027-c285346e541a\"\
        ,\"type\":\"dashboard\",\"name\":\"8\",\"fullyQualifiedName\":\"sample_superset.8\"\
        ,\"description\":\"\",\"displayName\":\"Orders dashboard\",\"deleted\":false}]"
  previousVersion: 1.5
  changeSummary: {}
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 432eefd2-1e7c-46fd-916a-7cd7fbe410f8
    type: dashboard
    name: 11
    fullyQualifiedName: sample_superset.11
    description: ""
    displayName: FCC New Coder Survey 2018
    deleted: false
  - id: 4564d142-6f2f-4a7c-8ff4-2d6397b82d06
    type: dashboard
    name: 34
    fullyQualifiedName: sample_superset.34
    description: ""
    displayName: Unicode Test
    deleted: false
  - id: 1a7bac61-6887-4614-8027-c285346e541a
    type: dashboard
    name: 8
    fullyQualifiedName: sample_superset.8
    description: ""
    displayName: Orders dashboard
    deleted: false
entityStatus: Unprocessed
