name: 924041f0-328f-4c68-876e-11878dd2a187
displayName: Overview
fullyQualifiedName: Tableau.924041f0-328f-4c68-876e-11878dd2a187
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/Superstore/Overview
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 10372a4bba5e5def8a4b55fd10ba9bf8
dashboards:
  - id: 84e3e3b0-c043-455f-a21e-8aa9d97fe142
    type: dashboard
    name: f3598b75-e0c8-4d50-99ee-5d230b7ec767
    fullyQualifiedName: Tableau.f3598b75-e0c8-4d50-99ee-5d230b7ec767
    displayName: Superstore
    deleted: false
entityStatus: Approved
