name: ac7069fe-ccf1-40c8-a903-1a5e4a919049
displayName: Order Details
fullyQualifiedName: Tableau.ac7069fe-ccf1-40c8-a903-1a5e4a919049
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/Superstore/OrderDetails
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 452fbfae2b2c7c43f10cf3ff0d8147c7
dashboards:
  - id: 84e3e3b0-c043-455f-a21e-8aa9d97fe142
    type: dashboard
    name: f3598b75-e0c8-4d50-99ee-5d230b7ec767
    fullyQualifiedName: Tableau.f3598b75-e0c8-4d50-99ee-5d230b7ec767
    displayName: Superstore
    deleted: false
entityStatus: Approved
