name: 5ff9a44e-570f-4098-9e8f-238051ccb96a
displayName: Technology
fullyQualifiedName: Tableau.5ff9a44e-570f-4098-9e8f-238051ccb96a
chartType: Other
sourceUrl: https://prod-uk-a.online.tableau.com/#/site/lafeg23917-004015dc22/views/WorldIndicators/Technology
owners: []
tags: []
service:
  id: 2de831d3-b697-426a-b7f7-045efd81b58c
  type: dashboardService
  name: Tableau
  fullyQualifiedName: Tableau
  description: ""
  displayName: Tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 0e0c741b9fac6780a004c5c5f2dfabbc
dashboards:
  - id: 0f8e11d2-f2b2-4f90-bf7c-292685d660f4
    type: dashboard
    name: c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    fullyQualifiedName: Tableau.c7b53d87-a8f3-4112-ad5d-bbbd9abeed13
    displayName: World Indicators
    deleted: false
entityStatus: Approved
