name: 4
displayName: Accounts SAMPLE
fullyQualifiedName: TestMetabase.4
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/4-accounts-sample
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 88f43270400b820aea936af23f764e7d
dashboards:
  - id: 43710413-21f3-41ac-bc1f-2441bfda2c03
    type: dashboard
    name: 2
    fullyQualifiedName: TestMetabase.2
    displayName: Delete evening test 2
    deleted: false
entityStatus: Approved
