name: 60f6cea4-db49-488b-bb9f-2e27fb87f024
displayName: Traffic and Adoption Drilldown
fullyQualifiedName: Test_tableau.60f6cea4-db49-488b-bb9f-2e27fb87f024
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AdminInsightsStarter/TrafficandAdoptionDrilldown
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: be1ab48c2557a0859fa530e14f9dde8d
dashboards:
  - id: f68c884f-5fff-4e02-a868-56c252de4435
    type: dashboard
    name: 223fd672-ec67-428b-a885-b87c7dd77c9d
    fullyQualifiedName: Test_tableau.223fd672-ec67-428b-a885-b87c7dd77c9d
    displayName: Admin Insights Starter
    deleted: false
entityStatus: Approved
