name: 2
displayName: Customers and Orders Query
fullyQualifiedName: TestMetabase.2
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/2-customers-and-orders-query
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 87597a7614c03ae47abdcc7fd018b710
dashboards:
  - id: 9ad5bcc7-7909-43fd-832e-2272ae80a710
    type: dashboard
    name: 1
    fullyQualifiedName: TestMetabase.1
    displayName: jaffle_shop dashboard
    deleted: false
entityStatus: Approved
