name: c623e976-61dc-43c2-84e3-54a8773c6a54
displayName: testpowerbi
fullyQualifiedName: test_pbi.c623e976-61dc-43c2-84e3-54a8773c6a54
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/reports/e8c09ad1-7335-490e-8b72-b657c5efe56f
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 77506ed651a6d3dea8bb0b911400553a
dashboards:
  - id: 509341d6-e121-451c-b836-54f60e4ff6ac
    type: dashboard
    name: 10b5fb06-2bc0-4634-9b56-f6edf9cddc50
    fullyQualifiedName: test_pbi.10b5fb06-2bc0-4634-9b56-f6edf9cddc50
    displayName: products dashboard
    deleted: false
entityStatus: Approved
