name: a89176fa-bc14-4788-ad5e-7ebcd2b92aa8
displayName: Business
fullyQualifiedName: Test_tableau.a89176fa-bc14-4788-ad5e-7ebcd2b92aa8
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/Business
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 8f950d1fecabdc415a3a0efb619a43b4
dashboards:
  - id: 1678d28a-92e8-420e-91de-13037e162c76
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: Test_tableau.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Approved
