name: 10bd7778-bcd0-4100-9bf7-d8e6552f5b44
displayName: Customers
fullyQualifiedName: Test_tableau.10bd7778-bcd0-4100-9bf7-d8e6552f5b44
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/Customers
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 4074d81a64574c35276d71172b9652de
dashboards:
  - id: 0b1360a8-5716-40cf-8030-d368a6a85655
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: Test_tableau.e6627edb-6cc8-408f-973d-df0e990f6434
    displayName: Superstore
    deleted: false
entityStatus: Approved
