name: a631e784-5a72-40dc-9550-71b24843b34f
displayName: Product
fullyQualifiedName: Test_tableau.a631e784-5a72-40dc-9550-71b24843b34f
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/Product
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: d7bd446a2a4ad8f5a731142ab52c2af6
dashboards:
  - id: 0b1360a8-5716-40cf-8030-d368a6a85655
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: Test_tableau.e6627edb-6cc8-408f-973d-df0e990f6434
    displayName: Superstore
    deleted: false
entityStatus: Approved
