name: 312dc4c2-7360-4e7c-ae8b-4da6e3102ae5
displayName: Tourism
fullyQualifiedName: test_tablue.312dc4c2-7360-4e7c-ae8b-4da6e3102ae5
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/Tourism
owners: []
tags: []
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: e6b454b25860a74118cdfb3832e5f8d3
dashboards:
  - id: 4f9cb6ea-140a-450d-bea0-1438124c9b52
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: test_tablue.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Unprocessed
