name: a091abf0-a2a6-4b72-8cb7-1a02dcb8cb1b
displayName: Sheet 1
fullyQualifiedName: test_tablue.a091abf0-a2a6-4b72-8cb7-1a02dcb8cb1b
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/FraudDetectionWorkbook/Sheet1
owners: []
tags: []
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 16cd6d0a329553f2537fdb99908505b6
dashboards:
  - id: 3650abcf-bceb-4846-b787-5b712de48351
    type: dashboard
    name: a92c2afc-a671-47ba-9fbc-1a50d469ac8a
    fullyQualifiedName: test_tablue.a92c2afc-a671-47ba-9fbc-1a50d469ac8a
    displayName: Fraud Detection Workbook
    deleted: false
entityStatus: Unprocessed
