name: 40fe43b7-8c53-40c6-afe1-26cea5cb7b51
displayName: Commission Model
fullyQualifiedName: Test_tableau.40fe43b7-8c53-40c6-afe1-26cea5cb7b51
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/CommissionModel
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: f0a3a6fa556035a72f9edafe94eb73bb
dashboards:
  - id: 0b1360a8-5716-40cf-8030-d368a6a85655
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: Test_tableau.e6627edb-6cc8-408f-973d-df0e990f6434
    displayName: Superstore
    deleted: false
entityStatus: Approved
