name: 29ec8a9c-8e08-4726-8818-de3f1ddfe30e
displayName: Forecast
fullyQualifiedName: test_tablue.29ec8a9c-8e08-4726-8818-de3f1ddfe30e
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/Forecast
owners: []
tags:
  - tagFQN: TableauTags.PII
    name: PII
    description: Tableau Tag
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 51ab836c7d6e78d4475fd98f11ad531e
dashboards:
  - id: 6382e1ad-6c27-456d-80fa-d9febb075d15
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: test_tablue.e6627edb-6cc8-408f-973d-df0e990f6434
    description: Updated workbook description via reverse ingestion test - WCCSTIXCISDPRYK
    displayName: Superstore
    deleted: false
entityStatus: Unprocessed
