name: d1b18d71-4414-4975-9f9c-fd49f21401d4
displayName: d1b18d71-4414-4975-9f9c-fd49f21401d4
fullyQualifiedName: test_pbi.d1b18d71-4414-4975-9f9c-fd49f21401d4
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/9feec07c-8ad3-42be-b8a2-b8effd0d326a
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: c93fc97eeb724bfb1235aa99965054cb
dashboards:
  - id: 0dda4b77-b69f-426d-b4ec-7c004db37baa
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: test_pbi.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
