name: 05f69d68-a6f1-4776-9b86-ba37e47ba4d6
displayName: Bad Hires (<60 Days of Employment)
fullyQualifiedName: test_pbi.05f69d68-a6f1-4776-9b86-ba37e47ba4d6
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/dashboards/87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
owners: []
tags:
  - tagFQN: Tier.Tier2
    name: Tier2
    description: |-
      **Important business datasets for your company (not as critical as Tier 1)**

      - Used in important business metrics, product metrics, and dashboards to drive internal decisions

      - Used in important compliance reporting to major regulators, govt entities, and third party

      - Used for less critical online user-facing experiences (user activity, user behavior)

      - Source used to derive other critical Tier-2 datasets
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1770014773521
    appliedBy: anujkumar.yadav
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
incrementalChangeDescription:
  fieldsAdded:
    - name: tags
      newValue: "[{\"tagFQN\":\"Tier.Tier2\",\"name\":\"Tier2\",\"description\":\"\
        **Important business datasets for your company (not as critical as Tier 1)**\\\
        n\\n- Used in important business metrics, product metrics, and dashboards\
        \ to drive internal decisions\\n\\n- Used in important compliance reporting\
        \ to major regulators, govt entities, and third party\\n\\n- Used for less\
        \ critical online user-facing experiences (user activity, user behavior)\\\
        n\\n- Source used to derive other critical Tier-2 datasets\",\"source\":\"\
        Classification\",\"labelType\":\"Manual\",\"state\":\"Confirmed\",\"appliedBy\"\
        :\"anujkumar.yadav\"}]"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
domains: []
dataProducts: []
sourceHash: 0b0f3f4904c8824c5e2a8f893f8165f5
dashboards:
  - id: 53394e37-6595-4544-816f-8846721ea07f
    type: dashboard
    name: 87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    fullyQualifiedName: test_pbi.87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    displayName: Human Resources Sample
    deleted: false
entityStatus: Approved
