name: 4ea28f5b-28a9-481f-95fd-235e3e50cc39
displayName: 4ea28f5b-28a9-481f-95fd-235e3e50cc39
fullyQualifiedName: test_pbi.4ea28f5b-28a9-481f-95fd-235e3e50cc39
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/dashboards/87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: d1591e0b395e17fbf361c5ebe76f47d9
dashboards:
  - id: 53394e37-6595-4544-816f-8846721ea07f
    type: dashboard
    name: 87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    fullyQualifiedName: test_pbi.87e77a28-0c0c-4cdc-ba8e-9c6668dc1025
    displayName: Human Resources Sample
    deleted: false
entityStatus: Approved
