name: 5
displayName: Customers and Orders Query
fullyQualifiedName: TestMetabase.5
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/5-customers-and-orders-query
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 48f7246e0d2dccd0e1098a342e442623
dashboards:
  - id: 43710413-21f3-41ac-bc1f-2441bfda2c03
    type: dashboard
    name: 2
    fullyQualifiedName: TestMetabase.2
    displayName: Delete evening test 2
    deleted: false
entityStatus: Approved
