name: d4a77102-7c8e-49ea-a487-6ce827cdeeea
displayName: What If Forecast
fullyQualifiedName: Test_tableau.d4a77102-7c8e-49ea-a487-6ce827cdeeea
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/WhatIfForecast
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: ec64dc498851482e8f2abf356a5a0f8a
dashboards:
  - id: 0b1360a8-5716-40cf-8030-d368a6a85655
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: Test_tableau.e6627edb-6cc8-408f-973d-df0e990f6434
    displayName: Superstore
    deleted: false
entityStatus: Approved
