name: 9caa869e-1fb7-4b7b-a3a6-b1e90a62742f
displayName: Product vs Category Dashboard
fullyQualifiedName: Test_tableau.9caa869e-1fb7-4b7b-a3a6-b1e90a62742f
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AnalyticsWorkbook/ProductvsCategoryDashboard
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
incrementalChangeDescription:
  fieldsAdded:
    - name: certification
      newValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Gold\",\"name\":\"Gold\"\
        ,\"description\":\"Gold certified Data Asset.\",\"style\":{\"color\":\"#FFCE00\"\
        ,\"iconURL\":\"GoldCertification.svg\"},\"source\":\"Classification\",\"labelType\"\
        :\"Manual\",\"state\":\"Confirmed\"},\"appliedDate\":1756213135454,\"expiryDate\"\
        :1758805135454}"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
domains: []
dataProducts: []
certification:
  tagLabel:
    tagFQN: Certification.Gold
    name: Gold
    description: Gold certified Data Asset.
    style:
      color: "#FFCE00"
      iconURL: GoldCertification.svg
    source: Classification
    labelType: Manual
    state: Confirmed
  appliedDate: 1756213135467
  expiryDate: 1758805135467
sourceHash: 60b2da82b9d0514fcf1cefccd00c286f
dashboards:
  - id: 62c8bad7-d60c-4e3e-a143-79832b03b129
    type: dashboard
    name: 6c602fd5-7a2c-4af5-881f-165d734c4169
    fullyQualifiedName: Test_tableau.6c602fd5-7a2c-4af5-881f-165d734c4169
    displayName: Analytics Workbook
    deleted: false
entityStatus: Approved
