name: 6
displayName: RED_Q
fullyQualifiedName: TestMetabase.6
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/6-red-q
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 7642425abdd7cdd0fd42ecbeb61ad399
dashboards:
  - id: 18cb0fab-de7d-4175-815b-6d59c8862fa2
    type: dashboard
    name: 3
    fullyQualifiedName: TestMetabase.3
    displayName: DEMO_DASH
    deleted: false
entityStatus: Approved
