name: 3
displayName: Customers and Orders Query
fullyQualifiedName: TestMetabase.3
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/3-customers-and-orders-query
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: e91fa53744634f0709e4dd8c0d390bb4
dashboards:
  - id: f11a1eee-27e0-45b1-87e2-8a23d84c5f03
    type: dashboard
    name: default
    fullyQualifiedName: TestMetabase.default
    displayName: default
    deleted: false
entityStatus: Approved
