name: bd47af65-41e6-4c48-a8b4-711ed1e84e53
displayName: Publish Event Drilldown
fullyQualifiedName: Test_tableau.bd47af65-41e6-4c48-a8b4-711ed1e84e53
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AdminInsightsStarter/PublishEventDrilldown
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: cf441f566f369c8996317bb95e2cf2b9
dashboards:
  - id: f68c884f-5fff-4e02-a868-56c252de4435
    type: dashboard
    name: 223fd672-ec67-428b-a885-b87c7dd77c9d
    fullyQualifiedName: Test_tableau.223fd672-ec67-428b-a885-b87c7dd77c9d
    displayName: Admin Insights Starter
    deleted: false
entityStatus: Approved
