name: 71f548a1-cdf2-41fb-a5bc-db637a2d1610
displayName: Sales Story
fullyQualifiedName: Test_tableau.71f548a1-cdf2-41fb-a5bc-db637a2d1610
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AnalyticsWorkbook/SalesStory
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 95d4154987f757544ccd0ab504600ab9
dashboards:
  - id: 62c8bad7-d60c-4e3e-a143-79832b03b129
    type: dashboard
    name: 6c602fd5-7a2c-4af5-881f-165d734c4169
    fullyQualifiedName: Test_tableau.6c602fd5-7a2c-4af5-881f-165d734c4169
    displayName: Analytics Workbook
    deleted: false
entityStatus: Approved
