name: e1aaf327-1aba-406b-85da-206d63a0ed5d
displayName: Sheet 1
fullyQualifiedName: test_tablue.e1aaf327-1aba-406b-85da-206d63a0ed5d
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AyushTestCSV/Sheet1
owners: []
tags:
  - tagFQN: '"Bug.Test".GlossaryTerm1'
    name: GlossaryTerm1
    displayName: GlossaryTerm1
    description: <p>GlossaryTerm1</p>
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '"Bug.Test".dataTerm'
    name: dataTerm
    displayName: dataTerm
    description: <p>dataTerm</p>
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '"Bug.Test".sampleGlossary102'
    name: sampleGlossary102
    displayName: ""
    description: <p>sampleGlossary102</p>
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: Certification.Silver
    name: Silver
    description: Silver certified Data Asset.
    style:
      color: "#ADADAD"
      iconURL: SilverCertification.svg
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: General.VATCode
    name: VATCode
    description: "VAT code or identification number. See [VAT Identification Number](https://en.wikipedia.org/wiki/VAT_identification_number)."
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: Glossary.Glossary-Term-2
    name: Glossary-Term-2
    displayName: ""
    description: Glossary-Term-2
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: MY_TAG.1
    name: 1
    description: SNOWFLAKE TAG VALUE
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: MY_TAG2ND_2.2nd eight
    name: 2nd eight
    description: SNOWFLAKE TAG VALUE
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: PII.Sensitive
    name: Sensitive
    description: "PII which if lost, compromised, or disclosed without authorization,\
      \ could result in substantial harm, embarrassment, inconvenience, or unfairness\
      \ to an individual."
    style:
      color: "#ff0000"
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: my_tag2nd.2nd_two
    name: 2nd_two
    description: SNOWFLAKE TAG VALUE
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: my_tag2nd_2.2nd eight
    name: 2nd eight
    description: SNOWFLAKE TAG VALUE
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: test_2_policy_tag.test_2_policy_tag
    name: test_2_policy_tag
    description: Bigquery Policy Tag
    source: Classification
    labelType: Derived
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
incrementalChangeDescription:
  fieldsAdded:
    - name: tags
      newValue: "[{\"tagFQN\":\"\\\"Bug.Test\\\".GlossaryTerm1\",\"name\":\"GlossaryTerm1\"\
        ,\"displayName\":\"GlossaryTerm1\",\"description\":\"<p>GlossaryTerm1</p>\"\
        ,\"style\":{},\"source\":\"Glossary\",\"labelType\":\"Manual\",\"state\":\"\
        Confirmed\"},{\"tagFQN\":\"\\\"Bug.Test\\\".dataTerm\",\"name\":\"dataTerm\"\
        ,\"displayName\":\"dataTerm\",\"description\":\"<p>dataTerm</p>\",\"style\"\
        :{},\"source\":\"Glossary\",\"labelType\":\"Manual\",\"state\":\"Confirmed\"\
        },{\"tagFQN\":\"\\\"Bug.Test\\\".sampleGlossary102\",\"name\":\"sampleGlossary102\"\
        ,\"displayName\":\"\",\"description\":\"<p>sampleGlossary102</p>\",\"style\"\
        :{},\"source\":\"Glossary\",\"labelType\":\"Manual\",\"state\":\"Confirmed\"\
        },{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\",\"description\"\
        :\"Silver certified Data Asset.\",\"style\":{\"color\":\"#ADADAD\",\"iconURL\"\
        :\"SilverCertification.svg\"},\"source\":\"Classification\",\"labelType\"\
        :\"Derived\",\"state\":\"Confirmed\"},{\"tagFQN\":\"General.VATCode\",\"name\"\
        :\"VATCode\",\"description\":\"VAT code or identification number. See [VAT\
        \ Identification Number](https://en.wikipedia.org/wiki/VAT_identification_number).\"\
        ,\"source\":\"Classification\",\"labelType\":\"Derived\",\"state\":\"Confirmed\"\
        },{\"tagFQN\":\"Glossary.Glossary-Term-2\",\"name\":\"Glossary-Term-2\",\"\
        displayName\":\"\",\"description\":\"Glossary-Term-2\",\"style\":{},\"source\"\
        :\"Glossary\",\"labelType\":\"Manual\",\"state\":\"Confirmed\"},{\"tagFQN\"\
        :\"PII.Sensitive\",\"name\":\"Sensitive\",\"description\":\"PII which if lost,\
        \ compromised, or disclosed without authorization, could result in substantial\
        \ harm, embarrassment, inconvenience, or unfairness to an individual.\",\"\
        style\":{\"color\":\"#ff0000\"},\"source\":\"Classification\",\"labelType\"\
        :\"Derived\",\"state\":\"Confirmed\"},{\"tagFQN\":\"test_2_policy_tag.test_2_policy_tag\"\
        ,\"name\":\"test_2_policy_tag\",\"description\":\"Bigquery Policy Tag\",\"\
        source\":\"Classification\",\"labelType\":\"Derived\",\"state\":\"Confirmed\"\
        }]"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.2
  changeSummary: {}
domains: []
dataProducts: []
sourceHash: b28618780288da90e3a6c393f02c8d39
dashboards:
  - id: 2dbc084f-0474-4d74-bbe0-30bdcf21dee8
    type: dashboard
    name: 050c80e6-263d-4bf1-88bd-ee38081525c3
    fullyQualifiedName: test_tablue.050c80e6-263d-4bf1-88bd-ee38081525c3
    displayName: AyushTestCSV
    deleted: false
entityStatus: Unprocessed
