name: e820f923-aafa-425d-bad5-21c5d81242d8
displayName: Technology
fullyQualifiedName: test_tablue.e820f923-aafa-425d-bad5-21c5d81242d8
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/Technology
owners: []
tags: []
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 341f580a9dd1ae3abb42870aa1dc0a9e
dashboards:
  - id: 4f9cb6ea-140a-450d-bea0-1438124c9b52
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: test_tablue.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Unprocessed
