name: 9448ca81-19de-4b9d-a526-2901da653500
displayName: 9448ca81-19de-4b9d-a526-2901da653500
fullyQualifiedName: test_pbi.9448ca81-19de-4b9d-a526-2901da653500
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/reports/06808307-e9b1-4661-8671-9866ad4e81b1
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 1e4cd0ad40439a13af8bed59b712299d
dashboards:
  - id: 583413ff-daad-4d8c-afa3-d21556b747a4
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: test_pbi.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
entityStatus: Approved
