name: ec90227b-2314-4158-a95a-ec1175b09ede
displayName: Sheet 1
fullyQualifiedName: test_tablue.ec90227b-2314-4158-a95a-ec1175b09ede
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/TestWorkbookAyush/Sheet1
owners: []
tags: []
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 30eec9b098bcfc8afae282f06f931d51
dashboards:
  - id: 495bba39-7917-4e9a-9405-b1193ee8c3a3
    type: dashboard
    name: 31c65de8-5a65-4776-b492-87c449920f07
    fullyQualifiedName: test_tablue.31c65de8-5a65-4776-b492-87c449920f07
    displayName: TestWorkbookAyush
    deleted: false
entityStatus: Unprocessed
