name: f93a06c9-1343-436e-995f-ce07649eb9e6
displayName: Order Details
fullyQualifiedName: Test_tableau.f93a06c9-1343-436e-995f-ce07649eb9e6
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/Superstore/OrderDetails
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 94f130153b5b4f717f5d7a252aecabf4
dashboards:
  - id: 0b1360a8-5716-40cf-8030-d368a6a85655
    type: dashboard
    name: e6627edb-6cc8-408f-973d-df0e990f6434
    fullyQualifiedName: Test_tableau.e6627edb-6cc8-408f-973d-df0e990f6434
    displayName: Superstore
    deleted: false
entityStatus: Approved
