name: a5c1f16c-bf87-4e09-bf4a-5fdb7636680a
displayName: Category Measure Sheet
fullyQualifiedName: Test_tableau.a5c1f16c-bf87-4e09-bf4a-5fdb7636680a
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AnalyticsWorkbook/CategoryMeasureSheet
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: e21a42a750f44a74886e540a1417e478
dashboards:
  - id: 62c8bad7-d60c-4e3e-a143-79832b03b129
    type: dashboard
    name: 6c602fd5-7a2c-4af5-881f-165d734c4169
    fullyQualifiedName: Test_tableau.6c602fd5-7a2c-4af5-881f-165d734c4169
    displayName: Analytics Workbook
    deleted: false
entityStatus: Approved
