name: 42a9c6d3-3530-425a-9827-0b761a33d5b2
displayName: User Drilldown
fullyQualifiedName: Test_tableau.42a9c6d3-3530-425a-9827-0b761a33d5b2
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AdminInsightsStarter/UserDrilldown
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: e5dd9e5c78a5eb647e6a7e2f136c755c
dashboards:
  - id: f68c884f-5fff-4e02-a868-56c252de4435
    type: dashboard
    name: 223fd672-ec67-428b-a885-b87c7dd77c9d
    fullyQualifiedName: Test_tableau.223fd672-ec67-428b-a885-b87c7dd77c9d
    displayName: Admin Insights Starter
    deleted: false
entityStatus: Approved
