name: 1
displayName: Orders Question
fullyQualifiedName: TestMetabase.1
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/1-orders-question
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 2f78ed440810f0ec55a65206e794cb16
dashboards:
  - id: 9ad5bcc7-7909-43fd-832e-2272ae80a710
    type: dashboard
    name: 1
    fullyQualifiedName: TestMetabase.1
    displayName: jaffle_shop dashboard
    deleted: false
entityStatus: Approved
