name: 7
displayName: "Customers, Count, Grouped by Customer ID: Auto binned"
fullyQualifiedName: TestMetabase.7
chartType: Bar
sourceUrl: https://metabase.apps.int.getcollate.io/question/7-customers--count--grouped-by-customer-id--auto-binned
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: f3f01dc8a5056751fc708a5a803d680d
dashboards:
  - id: 18cb0fab-de7d-4175-815b-6d59c8862fa2
    type: dashboard
    name: 3
    fullyQualifiedName: TestMetabase.3
    displayName: DEMO_DASH
    deleted: false
entityStatus: Approved
