name: 141233b0-6421-41dc-9dfb-eaa6ce6a6544
displayName: lineagetest
fullyQualifiedName: test_pbi.141233b0-6421-41dc-9dfb-eaa6ce6a6544
chartType: Other
sourceUrl: https://app.powerbi.com/groups/9d3cbb66-bdd8-4681-9ecf-acbe27fbccb5/reports/872e1f0c-500e-4e28-84d5-9eb067b4a05f
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: e24c91cd1c7b34715d2e1ac44f90f0d6
dashboards:
  - id: 6cec13e8-4ba6-44cf-a7fa-00de0837acee
    type: dashboard
    name: 4590880a-70e0-482f-8e10-480a3999b165
    fullyQualifiedName: test_pbi.4590880a-70e0-482f-8e10-480a3999b165
    displayName: Lineage Test 1 Dashboard
    deleted: false
entityStatus: Approved
