name: 82be01b5-87d3-4eb9-9f1c-be93478b12d3
displayName: Login Activity Drilldown
fullyQualifiedName: Test_tableau.82be01b5-87d3-4eb9-9f1c-be93478b12d3
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AdminInsightsStarter/LoginActivityDrilldown
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 3570d55304afa7815fc86afff22e5236
dashboards:
  - id: f68c884f-5fff-4e02-a868-56c252de4435
    type: dashboard
    name: 223fd672-ec67-428b-a885-b87c7dd77c9d
    fullyQualifiedName: Test_tableau.223fd672-ec67-428b-a885-b87c7dd77c9d
    displayName: Admin Insights Starter
    deleted: false
entityStatus: Approved
