name: faa94a4e-41e1-4015-9796-6f43b012fc2a
displayName: faa94a4e-41e1-4015-9796-6f43b012fc2a
fullyQualifiedName: test_pbi.faa94a4e-41e1-4015-9796-6f43b012fc2a
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/9feec07c-8ad3-42be-b8a2-b8effd0d326a
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: b598228d7e18c04edf9e67583115d0fa
dashboards:
  - id: 0dda4b77-b69f-426d-b4ec-7c004db37baa
    type: dashboard
    name: 9feec07c-8ad3-42be-b8a2-b8effd0d326a
    fullyQualifiedName: test_pbi.9feec07c-8ad3-42be-b8a2-b8effd0d326a
    displayName: Customer Profitability Sample
    deleted: false
entityStatus: Approved
