name: ea83902f-5990-49c5-ac3f-6ad3533b212f
displayName: Stats for Space Usage
fullyQualifiedName: Test_tableau.ea83902f-5990-49c5-ac3f-6ad3533b212f
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AdminInsightsStarter/StatsforSpaceUsage
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 7fbbd38d87a2b7f19cba953c213f5637
dashboards:
  - id: f68c884f-5fff-4e02-a868-56c252de4435
    type: dashboard
    name: 223fd672-ec67-428b-a885-b87c7dd77c9d
    fullyQualifiedName: Test_tableau.223fd672-ec67-428b-a885-b87c7dd77c9d
    displayName: Admin Insights Starter
    deleted: false
entityStatus: Approved
