name: 91092fce-1e54-4e81-a739-eaf34789aa88
displayName: Health Indicators
fullyQualifiedName: Test_tableau.91092fce-1e54-4e81-a739-eaf34789aa88
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/WorldIndicators/HealthIndicators
owners: []
tags: []
service:
  id: 98dfb9cd-c36e-4c3e-8139-577b30d2a373
  type: dashboardService
  name: Test_tableau
  fullyQualifiedName: Test_tableau
  description: ""
  displayName: Test_tableau
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 14377ad2426f4729fbe248b80c088b6d
dashboards:
  - id: 1678d28a-92e8-420e-91de-13037e162c76
    type: dashboard
    name: ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    fullyQualifiedName: Test_tableau.ba363ec6-aabc-4d05-bb20-6023c5d0bc4c
    displayName: World Indicators
    deleted: false
entityStatus: Approved
