name: 10
displayName: pgsql table connected que.
fullyQualifiedName: TestMetabase.10
chartType: Table
sourceUrl: https://metabase.apps.int.getcollate.io/question/10-pgsql-table-connected-que-
owners: []
tags: []
service:
  id: d16a9306-d407-42a8-ad8c-c3aaa786d0cd
  type: dashboardService
  name: TestMetabase
  fullyQualifiedName: TestMetabase
  description: ""
  displayName: TestMetabase
  deleted: false
serviceType: Metabase
domains: []
dataProducts: []
sourceHash: 0eb577640e0cdc6a6c68cc2fe17d281e
dashboards:
  - id: 2b15ea2b-8371-4f2e-b50c-1a9304ad1e7f
    type: dashboard
    name: 4
    fullyQualifiedName: TestMetabase.4
    displayName: postgres dashboard
    deleted: false
entityStatus: Approved
