name: 4583d928-a0ff-4867-b843-fe49d30e127a
displayName: Total Rejected Defect Quantity
fullyQualifiedName: test_pbi.4583d928-a0ff-4867-b843-fe49d30e127a
chartType: Other
sourceUrl: https://app.powerbi.com/groups/277ac9b2-f295-4a6e-ad6c-7d3b33c2e0cc/dashboards/059965af-3532-4da4-a532-2754721f5e27
owners: []
tags: []
service:
  id: 951e0b91-c656-418c-9cd7-bac2f4d50442
  type: dashboardService
  name: test_pbi
  fullyQualifiedName: test_pbi
  description: ""
  displayName: test_pbi
  deleted: false
serviceType: PowerBI
domains: []
dataProducts: []
sourceHash: 1ad87c886152633df2c533d547ab8435
dashboards:
  - id: 583413ff-daad-4d8c-afa3-d21556b747a4
    type: dashboard
    name: 059965af-3532-4da4-a532-2754721f5e27
    fullyQualifiedName: test_pbi.059965af-3532-4da4-a532-2754721f5e27
    displayName: Supplier Quality Analysis Sample
    deleted: false
entityStatus: Approved
