name: a5c1f16c-bf87-4e09-bf4a-5fdb7636680a
displayName: Category Measure Sheet
fullyQualifiedName: test_tablue.a5c1f16c-bf87-4e09-bf4a-5fdb7636680a
chartType: Other
sourceUrl: https://us-east-1.online.tableau.com#/site/collate/views/AnalyticsWorkbook/CategoryMeasureSheet
owners: []
tags:
  - tagFQN: TableauTags.Analytics
    name: Analytics
    description: Tableau Tag
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: TableauTags.workbook
    name: workbook
    description: Tableau Tag
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: cd4a5558-dc91-4b28-8bc2-38674fd29dec
  type: dashboardService
  name: test_tablue
  fullyQualifiedName: test_tablue
  description: <p>test</p>
  displayName: test_tablue
  deleted: false
serviceType: Tableau
domains: []
dataProducts: []
sourceHash: 57a8cab0eb277ca608f78c922a829ee4
dashboards:
  - id: 9b5288b5-a90e-4fc5-bfca-1cd2efafd736
    type: dashboard
    name: 6c602fd5-7a2c-4af5-881f-165d734c4169
    fullyQualifiedName: test_tablue.6c602fd5-7a2c-4af5-881f-165d734c4169
    displayName: Analytics Workbook
    deleted: false
entityStatus: Unprocessed
