name: 4
displayName: ""
fullyQualifiedName: local_redash.4
description: ""
chartType: Other
sourceUrl: https://redash.apps.int.getcollate.io/dashboards/4
owners: []
tags:
  - tagFQN: Tier.Tier2
    name: Tier2
    description: |-
      **Important business datasets for your company (not as critical as Tier 1)**

      - Used in important business metrics, product metrics, and dashboards to drive internal decisions

      - Used in important compliance reporting to major regulators, govt entities, and third party

      - Used for less critical online user-facing experiences (user activity, user behavior)

      - Source used to derive other critical Tier-2 datasets
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
service:
  id: b22c98d2-675c-4ab4-8ae1-d11015e78085
  type: dashboardService
  name: local_redash
  fullyQualifiedName: local_redash
  displayName: local_redash
  deleted: false
serviceType: Redash
domains: []
dataProducts: []
sourceHash: af46d3f035053b8313eb50ee41adfc28
dashboards:
  - id: 7112be15-1953-48b7-9442-84be55dbe781
    type: dashboard
    name: 4
    fullyQualifiedName: local_redash.4
    description: This dashboard contains order related to orders
    displayName: Orders Dashboard
    deleted: false
entityStatus: Approved
