name: KE41A751D4AB2DB61E4F809B75182FDEBW7BA194B1CB7E47B0891BD379E7742F75
displayName: 'Cluster Segmentation by Zip Code '
fullyQualifiedName: microstrategy_service.KE41A751D4AB2DB61E4F809B75182FDEBW7BA194B1CB7E47B0891BD379E7742F75
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 14e009a270312d8060c291df938712a8
dashboards:
  - id: c69300b4-dd07-4291-b7ae-4cf0d8e5ab16
    type: dashboard
    name: 8F86838E0149ED53E2EF0A911FE6724E
    fullyQualifiedName: microstrategy_service.8F86838E0149ED53E2EF0A911FE6724E
    displayName: Estate Market Analysis DEV
    deleted: false
entityStatus: Approved
