name: K3AED48B66942790E46E106B08CBBB688K584391E11E421ADD6E9448AF341DE06D
displayName: Visualization 1 copy copy copy
fullyQualifiedName: microstrategy_service.K3AED48B66942790E46E106B08CBBB688K584391E11E421ADD6E9448AF341DE06D
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 8686cd42c20b555b700c323937f28e27
dashboards:
  - id: 27269e89-748f-43fe-adc2-aede08c82b18
    type: dashboard
    name: B8E507B047721190C8D14F80F11A65D1
    fullyQualifiedName: microstrategy_service.B8E507B047721190C8D14F80F11A65D1
    displayName: Tec Parameters
    deleted: false
entityStatus: Approved
