name: K92B48DA711EB1F558E910080EF85720FK92B48FF511EB1F558E930080EF85720F
displayName: Visualization 1
fullyQualifiedName: microstrategy_service.K92B48DA711EB1F558E910080EF85720FK92B48FF511EB1F558E930080EF85720F
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 8d55f1da819f0acc35b0193333456867
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
