name: K0F35EDF962441DF0DAD1CA8D993D0DF8KC3BE3FDB834D26D8B4EBBF8312D2C1B0
displayName: Additional Demos
fullyQualifiedName: microstrategy_service.K0F35EDF962441DF0DAD1CA8D993D0DF8KC3BE3FDB834D26D8B4EBBF8312D2C1B0
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 1843c67a734eae3b8ee28f918d119563
dashboards:
  - id: 69b50877-d71f-4f86-8989-31022d94c339
    type: dashboard
    name: 88E7FAA3F749A397F1DDEB8AAA91ABAE
    fullyQualifiedName: microstrategy_service.88E7FAA3F749A397F1DDEB8AAA91ABAE
    displayName: Library of Demos dev
    deleted: false
entityStatus: Approved
