name: W103W139
displayName: CATEGORY PERFORMANCE
fullyQualifiedName: microstrategy_service.W103W139
chartType: Other
owners: []
tags: []
service:
  id: 807cfa94-767d-4ce4-9e5e-903ba736a7cb
  type: dashboardService
  name: microstrategy_service
  fullyQualifiedName: microstrategy_service
  displayName: microstrategy_service
  deleted: false
serviceType: MicroStrategy
domains: []
dataProducts: []
sourceHash: 5c9628f1d8e6e16c3ace9cc0a100509d
dashboards:
  - id: e3e30c8a-46a5-4857-bcc8-765a82c631dc
    type: dashboard
    name: 1F7524D9A140D56CA99069A91E944637
    fullyQualifiedName: microstrategy_service.1F7524D9A140D56CA99069A91E944637
    displayName: Retail DC General Store
    deleted: false
entityStatus: Approved
