name: chart_2
displayName: Chart 2
fullyQualifiedName: SampleLookerService.chart_2
description: This is a sample Chart for Looker
chartType: Bar
sourceUrl: http://localhost:8088/looker/explore/?form_data=%7B%22slice_id%22%3A%20166%7D
owners: []
tags: []
service:
  id: e5a46435-15e0-4b01-897a-1bc38d5f74e3
  type: dashboardService
  name: SampleLookerService
  fullyQualifiedName: SampleLookerService
  displayName: SampleLookerService
  deleted: false
serviceType: Looker
domains: []
dataProducts: []
dashboards:
  - id: a3fb94d1-5759-45d6-b83b-32edaf869efd
    type: dashboard
    name: customers
    fullyQualifiedName: SampleLookerService.customers
    description: This is a sample Dashboard for Looker
    displayName: Customers dashboard
    deleted: false
entityStatus: Unprocessed
