name: 127
displayName: Are you an ethnic minority in your city?
fullyQualifiedName: SampleSuperSetService.127
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20127%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 05ff13b9-5f56-4af9-ac23-638fc8820c6a
    type: dashboard
    name: 10
    fullyQualifiedName: SampleSuperSetService.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 8b675d9c-be4f-4836-8487-a3aaaf432872
    type: dashboard
    name: 12
    fullyQualifiedName: SampleSuperSetService.12
    description: ""
    displayName: Misc Charts
    deleted: false
  - id: 2295de76-4a99-4551-87e9-7287f9db6653
    type: dashboard
    name: 33
    fullyQualifiedName: SampleSuperSetService.33
    description: ""
    displayName: Slack Dashboard
    deleted: false
  - id: 31a1ecc6-928f-472c-9e7c-5b4d7daefec9
    type: dashboard
    name: 51
    fullyQualifiedName: SampleSuperSetService.51
    description: ""
    displayName: Video Game Sales
    deleted: false
entityStatus: Unprocessed
