name: 117
displayName: Age distribution of respondents
fullyQualifiedName: SampleSuperSetService.117
description: ""
chartType: Histogram
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20117%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 0d9cba41-8f73-49b1-a5bb-a0b5a13e0d36
    type: dashboard
    name: 31
    fullyQualifiedName: SampleSuperSetService.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
  - id: 7ddd8c41-cf2e-41e2-9c8e-0a496f84309d
    type: dashboard
    name: 9
    fullyQualifiedName: SampleSuperSetService.9
    description: ""
    displayName: COVID Vaccine Dashboard
    deleted: false
entityStatus: Unprocessed
