name: 114
displayName: "# of Games That Hit 100k in Sales By Release Year"
fullyQualifiedName: SampleSuperSetService.114
description: ""
chartType: Area
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20114%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 05ff13b9-5f56-4af9-ac23-638fc8820c6a
    type: dashboard
    name: 10
    fullyQualifiedName: SampleSuperSetService.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 2295de76-4a99-4551-87e9-7287f9db6653
    type: dashboard
    name: 33
    fullyQualifiedName: SampleSuperSetService.33
    description: ""
    displayName: Slack Dashboard
    deleted: false
entityStatus: Unprocessed
