name: 183
displayName: Average and Sum Trends
fullyQualifiedName: SampleSuperSetService.183
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20183%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: bb52a6df-b931-480d-873b-24039db82402
    type: dashboard
    name: 11
    fullyQualifiedName: SampleSuperSetService.11
    description: ""
    displayName: FCC New Coder Survey 2018
    deleted: false
  - id: 31a1ecc6-928f-472c-9e7c-5b4d7daefec9
    type: dashboard
    name: 51
    fullyQualifiedName: SampleSuperSetService.51
    description: ""
    displayName: Video Game Sales
    deleted: false
  - id: 207f6707-f5fc-4667-b0aa-7cb4a39908b5
    type: dashboard
    name: 8
    fullyQualifiedName: SampleSuperSetService.8
    description: ""
    displayName: Orders dashboard
    deleted: false
entityStatus: Unprocessed
