name: 180
displayName: Boy Name Cloud
fullyQualifiedName: SampleSuperSetService.180
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: bb52a6df-b931-480d-873b-24039db82402
    type: dashboard
    name: 11
    fullyQualifiedName: SampleSuperSetService.11
    description: ""
    displayName: FCC New Coder Survey 2018
    deleted: false
  - id: 3c41a364-6316-484f-a8f4-79015694695e
    type: dashboard
    name: 34
    fullyQualifiedName: SampleSuperSetService.34
    description: ""
    displayName: Unicode Test
    deleted: false
  - id: d4fb8e2a-f9e4-41cd-9303-34451ec6053c
    type: dashboard
    name: 45
    fullyQualifiedName: SampleSuperSetService.45
    description: ""
    displayName: USA Births Names
    deleted: false
entityStatus: Unprocessed
