name: 166
displayName: '% Rural'
fullyQualifiedName: SampleSuperSetService.166
description: <p>descc</p>
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20166%7D
owners: []
tags: []
service:
  id: c5a05aca-c289-49af-a124-713b9777853c
  type: dashboardService
  name: SampleSuperSetService
  fullyQualifiedName: SampleSuperSetService
  displayName: SampleSuperSetService
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: description
      oldValue: ""
      newValue: <p>descc</p>
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
domains: []
dataProducts: []
dashboards:
  - id: 05ff13b9-5f56-4af9-ac23-638fc8820c6a
    type: dashboard
    name: 10
    fullyQualifiedName: SampleSuperSetService.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 0d9cba41-8f73-49b1-a5bb-a0b5a13e0d36
    type: dashboard
    name: 31
    fullyQualifiedName: SampleSuperSetService.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
entityStatus: Unprocessed
