name: 132
displayName: postgres_chart
fullyQualifiedName: SuperSet.132
chartType: Pie
sourceUrl: http://ec2-3-142-98-17.us-east-2.compute.amazonaws.com:8080/superset/explore/?form_data=%7B%22slice_id%22%3A%20132%7D
owners: []
tags: []
service:
  id: 96b2c37d-8d8c-4ef1-8bef-1c4fd361dffd
  type: dashboardService
  name: SuperSet
  fullyQualifiedName: SuperSet
  description: ""
  displayName: SuperSet
  deleted: false
serviceType: Superset
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
  - id: 761f0a12-7b08-4889-acc3-b8d4d11a7865
    type: domain
    name: domain.with.dot
    fullyQualifiedName: '"domain.with.dot"'
    description: domain.with.dot
    displayName: domain.with.dot
    inherited: true
dataProducts: []
dashboards:
  - id: 422c625c-6a5b-4e69-a5fa-b21205b68db1
    type: dashboard
    name: 15
    fullyQualifiedName: SuperSet.15
    displayName: "[ untitled dashboard ]"
    deleted: false
  - id: 9ff10f4d-be38-4da6-95f4-394eb89ea5a8
    type: dashboard
    name: 16
    fullyQualifiedName: SuperSet.16
    displayName: postgres_dash
    deleted: false
entityStatus: Approved
